### ISSUE TITLE
[eth-daemon] Implement eth daemon

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#10]
## Feature / Issue
We need the eth daemon lightnode since we need to access the ETH network. 

## Acceptance criteria
- [x] Implement a start method were the config can be passed as an json object. 
- [x] Implement a stop method that will stop the daemon

## Additional information
Pls keep in mind to update the doc's.

**Comment by julescoin** [comment]
please can someone help me with a lost eth transaction , it was pending for ages on my ether wallet then I made mistake of sending a zero transaction to my self now my 10eth are lost in space the 0 transaction worked but fully cancelled out my 10eth and completely not credited back...who wants to be my hero and help????

**Comment by albertoestarrona** [comment]
Done according the "React-native-eth-daemon"
