### ISSUE TITLE
support for existing languages

### ISSUE THREAD

**Issue by EvertonMelo** [Bit-Nation/BITNATION-Pangea-mobile#101]
please do not make the mistake below:

https://github.com/Bit-Nation/Pangea-Docs/pull/37

the source code and the documentation, are even reviewed?

**Comment by florianlenz** [comment]
Which mistake exactly? Reviewed in what regard? Spelling mistakes? I18n is not scoped till now but I can Imaging that we will implement it by the end of 2018.

**Comment by EvertonMelo** [comment]
hi, @florianlenz 

take care with 'Spelling mistakes' 
Little mistakes can make all your effort be empty. 
I have reported other errors but the maintainer has more to do but to correct

do not do this with people who contribute to your project,
since to drop something, says more than small mistakes.

and if you can tell the maintainer of Doc, that in Brazil you have become a joke.
both by official events that are canceled and do not warn anyone,
(https://www.youtube.com/watch?v=b7IhbxuFVqE)
and
(https://www.meetup.com/en-US/Bitnation-Brasilia-Decentralized-P2P-Governance-Services/events/246502284/)

how to create a language that does not exist.
I hope my information is useful to you, because it is sad to see a good project getting lost for several small mistakes.
and even official information.

**Comment by florianlenz** [comment]
@EvertonMelo I am sorry regarding the meeting's. 
Re the spelling mistakes, we will probabbly take care of them by the end of the year since we have more important things that we have to focus on right now. Feel free to open an PR that fix the mistake.
