### ISSUE TITLE
Data Structure: Use codes instead of text for fields in databases

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#106]
## Feature / Issue
> Descriptive text is a poor choice for known values in datebases, for many reasons (search, coding, comparison).

## Acceptance criteria
- [ ] Create a standard table of codes for known values in our databases, e.g. "No Law Enforcement System" = 0

## Additional information
Already, we are having trouble. To check if there is a law enforcement system, we have to compare the Nation field value to "No Law Enforcement System". One typo, or a change of that text, and the code breaks. If we want to change the UI-facing text, for whatever reason, the code breaks.
This is just bad architecture!

**Comment by florianlenz** [comment]
I will close this. @mimetic I am tired of this kind of conversation with you. Look at slack why we will NOT use.
