### ISSUE TITLE
[tests] `actions/nations.js` 

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#116]
## Acceptance criteria
- [x] Add test's for `actions/nations.js`
- [ ] updated doc's (in code) what this file is about.

**Comment by SeniorMobileDeveloper** [comment]
I have added tests for actions/nations.js. Please take a look by pulling from feature/unit-test.
@florianlenz could you tell me where to update the doc in the code?
