### ISSUE TITLE
[ui] Add the dashboard

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#12]
## Feature / Issue
> As a user I would like to see a dashboard when I open the app that show's different thing's like my wallet balance and so on. 
 ### Resources
>There must be mosaic code somewhere. However, see this code for a possible solution to the mosaic layout (for now) : https://github.com/GeekyAnts/react-native-easy-grid/commit/a6fa69462998333d951a404f0d5aa329b1a08da7

### Newest UI Design screens
https://invis.io/HTF508H5Z
(Contact David Gross for permissions)

## Acceptance criteria
- [ ] Should resize according to the screen size.
- [ ] The component's should be reusable. 
- [ ] Elements are "panels." Each panel contains a title and information, e.g. "Nations" and text.
- [ ] Not all panels must function. To show ideas, we can make fake panels but add "DEMO" to the background of the panel.
- [ ] The text and/or list of items is a sub-component, containing either a styled text block, a table, or an image
- [ ]  Code suggestion from David: Write the code each so that it can hold a multimedia element, or a link to one. That might be a styled text, image(s), a link to a video, or audio, or a web page, etc. I suggest the panel is given a database reference that points to a record (which can be cached!). That record contains the multimedia information or references necessary. This approach moves creation of the multimedia panels to some other system, and allows faster caching and checking for updates.
- [ ] Panels color and size can change based on variables that reflect age, importance of information, and amount of content. For example, an important news item about your nations should make the Nations panel larger, at the top-left, and more saturated color. How this should work, I do not know yet.
- [ ] Example of JS code to draw a Responsive, dynamic Tile Grid Layout (with many more examples in links below): https://www.jqueryscript.net/layout/Responsive-Dynamic-Tile-Grid-Layout-with-jQuery-tileWall.html

**Comment by kentdahlgren** [comment]
Faisal: the dashboard can be presented as a demo, and the content driven by links, and as such: is not as high of priority as the other screens. We should aspire to wrap this up today so we can switch to something else.

**Comment by kentdahlgren** [comment]
e.g. the Nations panel can have a button they tap to get to nations, and nothing more.

**Comment by mimetic** [comment]
Florian, Faisal:
In the UI designs, the original concept AND an updated version exist. You will need to collaborate to decide exactly what information, and which panels, you can show. Anything you cannot create, but wish to demonstrate, can be a "fake" panel with the word "DEMO" in the background.
