### ISSUE TITLE
Add a splash screen

### ISSUE THREAD

**Issue by faisal3413** [Bit-Nation/BITNATION-Pangea-mobile#14]
## Feature
> As a user I can see the splash screen when app open

## Acceptance criteria
- App should show a splash screen on loading

## Resources
In comments, below, is a JPG of a useable splash screen.

**Comment by mimetic** [comment]
Attached is a usable launch screen in high resolution.

![launch](https://user-images.githubusercontent.com/30195/34424634-b8100888-ebea-11e7-9178-fe2df1aeed27.jpg)

**Comment by mimetic** [comment]
Here is the same background, more compressed. Smaller JPG file than the previous version (v3)

![background-v3a](https://user-images.githubusercontent.com/30195/34449451-eb8e00ce-ecbd-11e7-905a-72f5a9674a21.jpg)

**Comment by mimetic** [comment]
Here is the same "launch" or "splash" screen, JPG compressed more to make a smaller file.
![launch](https://user-images.githubusercontent.com/30195/34449476-31525290-ecbe-11e7-80ce-15c0be20eeb3.jpg)

**Comment by kentdahlgren** [comment]
Who is assigned this task? I think we learned that this isn't the same as the static screens we wanted to present before. Else users end up with a "white page."

**Comment by albertoestarrona** [comment]
Yes, on both versions
