### ISSUE TITLE
[refactor] src/global/Colors.js

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#143]
## Feature / Issue
We have to refactor `src/global/Colors.js`.

## Acceptance criteria
__!!! Make sure to write the test's firs to avoid unexpected result's after the refactoring__
- [x] Refactor `var` to const and improve the quality of the software
- [x] File name must be lowerCamelCase
- [x] Add test's

**Comment by SeniorMobileDeveloper** [comment]
Finished and merged to develop branch.
