### ISSUE TITLE
[tools] fastlane for signing / building 

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#15]
## Feature / Issue
> As a developer I need an easy way to sign my project for ad-hoc build's and releases.

## Acceptance criteria
- [ ] Sign code for development / ad-hoc
- [ ] Sign code for releases

**Comment by mimetic** [comment]
Here are screenshots for store submission:

![intro-screen-2](https://user-images.githubusercontent.com/30195/34469352-92b25d34-eee2-11e7-918f-89f96f274b86.jpg)
![nation-create](https://user-images.githubusercontent.com/30195/34469353-92c2b3c8-eee2-11e7-8644-d2a6b759f7c7.jpg)
![profile-edit](https://user-images.githubusercontent.com/30195/34469354-92d2bffc-eee2-11e7-8f5c-ab69a05a0038.jpg)
![profile-view](https://user-images.githubusercontent.com/30195/34469355-92e51814-eee2-11e7-8f51-bfca453ca723.jpg)
![wallet-send](https://user-images.githubusercontent.com/30195/34469356-92f39542-eee2-11e7-88ef-9d9ec93a95b6.jpg)

**Comment by seland** [comment]
@florianlenz Is that issue finished? I suggest to close it.
