### ISSUE TITLE
Nation contract not sent to Ethereum chain

### ISSUE THREAD

**Issue by xsttx** [Bit-Nation/BITNATION-Pangea-mobile#167]
## Feature / Issue
After finishing filling in the nation form, the app shuts down, instead of sending the contract to the Ethereum chain. Which only saves the nation locally, not on the application for others to see or join.

## Acceptance criteria
- [Contract gets sent and executed on chain]

## Additional information
Phone used for this was Huawei

**Comment by florianlenz** [comment]
@xsttx I created an issue [here](https://github.com/corymsmith/react-native-fabric#crashlytics-usage) which already contain's an debug log. I will close this issue since this is just an follow up of the initial problem. Feel free to reopen it if it still happen's in the next release :)
