### ISSUE TITLE
[nation] join is shown't tho nation is not created

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#175]
## Issue
Hi, 
at the moment the join button of a nation is shown even if it's not created. You should only show a join button if the nation was written to the blockchain. You can check it by proving if the `idInSmartContract` is >= 0. Have a look at the database schema: http://bitnation-pangea-libs.readthedocs.io/en/develop/schemata/#nationschema

**Comment by seland** [comment]
Closed #179.
