### ISSUE TITLE
[nations] new functions for Nations on Pangea libs

### ISSUE THREAD

**Issue by albertoestarrona** [Bit-Nation/BITNATION-Pangea-mobile#180]
## Feature / Issue
> Due the new functionality for Nations on for 0.3.2 we need new functions on Pangea libs to support them

## Acceptance criteria
Functionality for:
- [x] Save a Draft Nation
- [x] Edit a Draft Nation
- [x] Delete a Draft Nation
- [x] Submit a Nation to the Blockchain
- [x] Know the status of a Nation

**Comment by florianlenz** [comment]
You can pull in the latest version with contain's the functionality by installing this branch: `npm install --save https://github.com/Bit-Nation/BITNATION-Pangea-libs#7f01979a2057998615a3f09e848ea34859015c50`. You can find the doc's and API here: http://bitnation-pangea-libs.readthedocs.io/en/develop/interfaces/#nationinterfacesrcethereumnationjs

**Comment by seland** [comment]
@florianlenz Any updates on a function to check status of a nation?

**Comment by seland** [comment]
It's already implemented and working.
