### ISSUE TITLE
[dashboard] msg queue

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#181]
## Feature / Issue
> As a use I need an activity log. 

Hi, in order to implement the activity log you need to keep the following in mind: 

1. The activity log will change during the runtime of the app. In order to update the state you need to listen for the `messaging_queue:job:added` event which is emitted by the event emitter (you can import the `MESSAGING_QUEUE_JOB_ADDED` constant from src/events.js). 

2. You should call `fetchMessages` to get the latest `X` messages. You will get an array of object's that with the following prop's: http://bitnation-pangea-libs.readthedocs.io/en/develop/schemata/#messagejobschema

**Comment by seland** [comment]
It's already implemented in latest develop.
