### ISSUE TITLE
[reminder] new tr

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#182]
## Feature / Issue
- We need to update the current i18n files with the new key's returned by pangea lib's and to update the existing function's to work with that key's

**Comment by seland** [comment]
@florianlenz Where can we find possible values for what translation keys pangea libs can return?

**Comment by florianlenz** [comment]
A lot of them are here: https://github.com/Bit-Nation/BITNATION-Pangea-libs/blob/develop/src/transKeys.js

**Comment by seland** [comment]
Since pangea libs is not used anymore, we can close that.
