### ISSUE TITLE
Chat: Update UI of Chat for 0.3.2

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#183]
## Feature / Issue
> Need a demonstration of chat for 0.3.2
> No one knows how to use chat library!

## Acceptance criteria
- [x] Learn how the current chat library
- [x] Learn how to change styles (color, font, etc.) in chat
- [x] Using global styles, make chat look like the design provided by David

## Additional information

**Comment by SeniorMobileDeveloper** [comment]
Modified the styles so that the chat look like the design provided by David. In branch fix/ui_chat

**Comment by seland** [comment]
Closed by #191.
