### ISSUE TITLE
[ui] Toolsbars in Nations View

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#185]
## Feature / Issue
There should be two different toolbars in Nation View (one for active nation, one for a draft nation). See UX and UI.
Toolsbars should be at bottom of screen, replacing navigation Tab bar.

## Acceptance criteria
- [x] Create toolbar for Nation View (active nation)
- [x] Create toolbar for Nation View (draft nation)
- [x] Position toolbars at bottom (remove navigation Tab Bar)

**Comment by albertoestarrona** [comment]
Ready in branch `feature/Nations-Detail-Screen-0.3.2`
