### ISSUE TITLE
[ui] Toolbar for Nation Create

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#186]
## Feature / Issue
> UX/UI specify a toolbar at the bottom of the screen for Nation Create.

## Acceptance criteria
- [x] Create Nation Create toolbar
- [x] Position at bottom of screen, remove navigation Tab bar

**Comment by albertoestarrona** [comment]
This is solved in branch `feature/New-Create-Nations-UI`
