### ISSUE TITLE
[ui] Normalizer(): globalize this function

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#187]
The "normalizer" function is great. It gives us "responsive" sizing for different devices. However, the sizing is hard-coded and not documented.

For example, we have resizing at 568, 667, and 736 heights, and these are hard-coded into the utility. I suggest these hard-coded values be in the global constants file.

Also, sizes seem to be hard-coded to a fixed size, e.g. height=== 568. Shouldn't these be set to height <= 568?

- [x] Move the screen sizing parameters to a global location, so it is easy to update or edit. Suggested: global Constants.js
- [x] Make resizing for sizes less than, and greater than, certain sizes
- [x] Document the breaks so we know what they mean, e.g. iPhone 5 vs. iPhone 8 vs. iPhone X vs. Android
- [x] Idea: create a "switch" to turn OFF all resizing for debugging/testing. Because, if I am working with an iOS simulator, it is hard to know what is resized and what isn't. Perhaps the switch is in constants? Or in the file?

**Comment by albertoestarrona** [comment]
Solved with #328
