### ISSUE TITLE
[ui] Dashboard Wallet Panel: layout code

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#188]
## Feature / Issue
> The layout of the wallet panel does not match the design, and it cannot be fixed with style changes.

## Acceptance criteria
- [x] Change the layout of the wallet panel on the dashboard so it looks like the UI design, and it can be styled.

![screen shot 2018-02-10 at 11 20 09 am](https://user-images.githubusercontent.com/30195/36065773-68123e78-0e54-11e8-9394-6f4e90eb9723.jpg)

**Comment by seland** [comment]
@mimetic It's update on feature/dashboard branch, please pull (or cherry pick [this](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/commit/fe418a937a90ca1d1d50513c65ac6a51a179a1ee) commit)

**Comment by mimetic** [comment]
Thanks. I got something working (very similar).
