### ISSUE TITLE
Interaction Flow: Private Key controls flow

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#19]
## Existance of private key controls flow
> As a user, if you do not have a private key, then you cannot have a wallet, nor create a nation.
> You will be warned to get a private, and/or be guided to create a private key.
[Private Key Flow Notes.pdf](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/files/1591413/Private.Key.Flow.Notes.pdf)

## Acceptance criteria
- [ ] Nations: "New" link shows either correct alerts or leads to "Create Nation".
- [ ] Wallets: software shows either "Create Wallet" or "Wallets List"

## Additional information
In the future, there may be different private keys for different activities, e.g. nation-building, wallets, documents. Expect more decision making like this to come, especially with the implementation of a simple "Key Chain".

**Comment by kentdahlgren** [comment]
Assigning to Andrew (who is working on wallet)

**Comment by seland** [comment]
Closed in release/0.3.1 branch.
