### ISSUE TITLE
[UI] iPhone X

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#190]
## Feature / Issue
> Layout fails with iPhone X
> There is an API to solve this: https://medium.com/react-native-training/react-native-iphonex-92ff511282af

## Acceptance criteria

* [x] Layout looks OK with iPhone X

## Additional information
https://medium.com/react-native-training/react-native-iphonex-92ff511282af

## From the website (above):
In version 0.50.1, the React Native team introduced a new API for easily dealing with the new iPhone X layout. This API is the SafeAreaView.
With SafeAreaView, you can easily update your existing codebase to be integrated with the iPhone X without a lot of headache.
Here’s how you can use it:

```
import {
...
SafeAreaView
} from 'react-native';
class Main extends React.Component {
render() {
return (
<SafeAreaView style={styles.safeArea}>
<App />
</SafeAreaView>
)
}
}
const styles = StyleSheet.create({
...,
safeArea: {
flex: 1,
backgroundColor: '#ddd'
}
})
```

What has worked for me for existing apps is to just set some background color that works well with your existing app design, in the above example that is a light gray, and flex: 1. We then just wrap the top level UI component of our app in the SafeAreaView and we’re good to go.

**Comment by albertoestarrona** [comment]
We solved this without using the SafeAreaView. Solved in branch `feature/iPhoneX-fix-0.3.2`
