### ISSUE TITLE
[UI]: Create Key: Font color below boxes is dark

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#194]
## Feature / Issue
> In the Create Wallet (secret key) pages, the text below the fields in the grid of words is too dark. It should be lighter, like the invisionapp.com designs.

## Acceptance criteria
- [ ] Lighten color of text of the CURRENT row to #F1F1F1
- [ ] Other numbers should be about the same color as the inactive fields.

Example attached:
![screen shot 2018-02-13 at 1 09 37 pm](https://user-images.githubusercontent.com/30195/36173851-366cffc6-10bf-11e8-90ba-e392210fed9c.jpg)

**Comment by seland** [comment]
Closed by #203.
