### ISSUE TITLE
[nation] update create / join / leave

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#198]
## Feature / Issue
We updated the `create` / `join` api. Please update it in the mobile app. To get the latest changes run `npm install https://github.com/Bit-Nation/BITNATION-Pangea-libs#7bca76b3e764156286d2e9c2a3cae9e82eabbbef `. Pay attention to the join / leave method. You should now pass in the whole nation as an argument. 

## Acceptance criteria
- [x] update join method
- [x] update leave method
- [x] When the join / leave button is grey - it's still touchable (bug)
- [x] The join / leave button should be gray when `nation.tx.status !== 200` since that mean's an state mutate is still pending.

**Comment by seland** [comment]
It's working after #261 merged.
