### ISSUE TITLE
App style (consistent throughout)

### ISSUE THREAD

**Issue by kentdahlgren** [Bit-Nation/BITNATION-Pangea-mobile#2]
## Feature / Issue
This ticket pertains to the application's look and feel. Specifically, the:
- fonts
- color palate
- background image

## Acceptance criteria
This issue is complete when every screen in the application utilizes the approved styling, pertaining to fonts, sizing, colors, and background image. 

Application must take into account customization conventions regarding sizing, fonts, etc

## Newest UI Design Screens
https://invis.io/HTF508H5Z

## Additional information
See attached.

For clarification, contact Kent (@florianlenz can you add me so I can tag myself pls?)

Latest colors and styles can be found in the Newest UI Design Screens.

**Comment by mimetic** [comment]
Here is the version 3 background image in high-resolution. (If there are changes, I will upload a new file and the version number will increase.)

![background-v3](https://user-images.githubusercontent.com/30195/34421004-5d325866-ebd2-11e7-9ff7-c71025c5d5ac.jpg)
