### ISSUE TITLE
Need to update software screenshots and description in the app store with each release

### ISSUE THREAD

**Issue by xsttx** [Bit-Nation/BITNATION-Pangea-mobile#209]

**Comment by xsttx** [comment]
Additionally, the version number says 1 (although it's 0.3.2)

**Comment by albertoestarrona** [comment]
Updated screenshots with actual version 0.3.2

About the version number in store (1.0) need to investigate if we'll be able to change it now to 0.3.2 because will decrease the published number.

**Comment by mimetic** [comment]
@florianlenz I cannot provide Android screen shots, because I cannot test on Android. However, let me know if you need assistance with this, and I will find a solution for you.

**Comment by xsttx** [comment]
I think @albertoestarrona did the screenshot update already. I'm happy to help @albertoestarrona with the text if needed?

**Comment by albertoestarrona** [comment]
@mimetic This is already solved

**Comment by xsttx** [comment]
@albertoestarrona do you want to work together on the app store texts?

**Comment by albertoestarrona** [comment]
@xsttx We can improve all the texts in the store, so if you can help me with that would be great

**Comment by mimetic** [comment]
@albertoestarrona @xsttx Please close this issue if it is resolved.

**Comment by xsttx** [comment]
Yep, let's close it and continue on Slack.
