### ISSUE TITLE
[lint] /src/components/common/

### ISSUE THREAD

**Issue by seland** [Bit-Nation/BITNATION-Pangea-mobile#213]
## Files to fix
 - [x] `NationActionButton.js`
 - [x] `PanelViewAlert.js`
 - [x] `PanelViewCitizen.js`
 - [x] `SwitchLabeled.js`

## Acceptance criteria
npm run lint should pass on corresponding files.

**Comment by albertoestarrona** [comment]
Solved with PR #238
