### ISSUE TITLE
[lint] /src/components/MultiSelect/

### ISSUE THREAD

**Issue by seland** [Bit-Nation/BITNATION-Pangea-mobile#215]
## Files to fix
 - [x] `index.js`

Since it's an external library, consider installing it via npm an remove source code from the Pangea project at all.

## Acceptance criteria
npm run lint should pass on corresponding files or files is moved to external dependencies.

**Comment by albertoestarrona** [comment]
We needed to customize a lot of the core styles of this component to meet the requirements of Adrian's design, that's why we integrated to the project instead of just installing it via npm
