### ISSUE TITLE
[panthalassa] jest + babel don't transpile from node_modules

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#23]
## Issue
Panthalassa (an external lib) is mostly written in flow (flow is an opt in type checker (like typescript)). When I start the project with `yarn run ios` it's starting correct (no transpile errors). BUT when I run the test's I am getting this error: 

```
Test suite failed to run

/Users/florian/project/BITNATION-Pangea-mobile/node_modules/BITNATION-Panthalassa/src/specification/secureStorageInterface.js:7
export interface SecureStorage {
^^^^^^

SyntaxError: Unexpected token export

34 | return sSImplementation;
35 |
> 36 | }
37 |

at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:318:17)
at Object.<anonymous> (src/services/panthalassa/secureStorage.js:36:181)
at Object.<anonymous> (__tests__/src/services/panthalassa/secureStorage.js:1:109)
```

Basically jest don't use babel correctly. 

## Acceptance criteria

* [ ] External flow files should be transpiled as well.

**Comment by seland** [comment]
@florianlenz Is that still happens?

**Comment by florianlenz** [comment]
Nope, solved.
