### ISSUE TITLE
Application crashes when tapping "newest nation" on the Dashboard screen

### ISSUE THREAD

**Issue by xsttx** [Bit-Nation/BITNATION-Pangea-mobile#233]
## Feature / Issue
When tapping on the "newest nation" on the Dashboard screen, instead of going to that nation, the app shuts down. 

## Acceptance criteria
When touching the nation it should lead to the screen of that nation

## Additional information
Could possibly have something to do with the time it takes for it to appear on chain?

**Comment by xsttx** [comment]
In addition, once the app re-opens after closing down, the entire nation menu screen appears to be a black screen.

**Comment by lchabin** [comment]
In addition, BitNations does not appear in Newest Nations from the start, it seems to appear randomly after some time after clicking several times on menus. This is not the proper way to inform a user in a GUI. It should display searching... or something to make you understand it is going to update. 
And of course PANGEA crashes.

**Comment by florianlenz** [comment]
Fixed.
