### ISSUE TITLE
Integrate more of Adrians latest grey/ yellow design scheme for next sprint

### ISSUE THREAD

**Issue by xsttx** [Bit-Nation/BITNATION-Pangea-mobile#234]
![bitnation_pangea_newdesign_03_grayyellow_1024](https://user-images.githubusercontent.com/17184469/36614321-88f9bfa2-18dc-11e8-905e-a68f6ef41adb.jpg)

Preferably without the blue menu (to similar to FB, Twitter, etc).

**Comment by mimetic** [comment]
Not enough information for action here. When we have a clear design decision and UI sketches, we can make this an action item in Github.
