### ISSUE TITLE
[UX/UI] More button on dashboard needs to link to website page.

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#246]
## Feature / Issue
> When a user presses the "More" button on the dashboard, in the "Notice" panel, it should open a web browser to a page on the Pangea website explaining this problem in detail.

## Acceptance criteria
- [ ] User touches More button and app opens browser to the website page.

## Additional information
Someone needs to handle the website part of this!

**Comment by seland** [comment]
Button was removed from dashboard, so closing the issue.
