### ISSUE TITLE
[UX/UI] Website page for "More" button in dashboard

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#247]
## Feature / Issue
> When a user presses the "More" button on the dashboard, in the "Notice" panel, it should open a web browser to a page on the Pangea website explaining this problem in detail.
> We need this page for our tech users who will be upset if they discover we are changing smart contracts without telling them. 

## Acceptance criteria
- [ ] Page on Pangea website created explaining that smart contracts will be upgraded in the future.

## Additional information
You must inform the UI/UX team of the website page URL

**Comment by seland** [comment]
More button was removed from dashboard, so closing.
