### ISSUE TITLE
[UI] Nation details screen

### ISSUE THREAD

**Issue by seland** [Bit-Nation/BITNATION-Pangea-mobile#251]
## Feature / Issue
Nation details screen needs some UI adjustments:
 - [x] Status panel contains extra whitespace after 'Status: '. Please remove it from the translations file (screenshot 1)
 - [x] Citizen panel contains extra whitespace after 'You are a citizen of'. Please remove it from the translations file (screenshot 1)
 - [x] Values are being escaped (notice &#x2F; text on Governmental Structure on screenshot 2), so look pretty ugly. 

<img width="286" alt="screen shot 2018-03-02 at 12 01 27 pm" src="https://user-images.githubusercontent.com/1781125/36893962-90aaa24e-1e12-11e8-9665-f80f54ad1d2f.png">
<img width="286" alt="screen shot 2018-03-02 at 12 01 51 pm" src="https://user-images.githubusercontent.com/1781125/36893964-93de7a6c-1e12-11e8-994a-1fcb4d962aa0.png">

## Acceptance criteria
All checkpoints are done.

**Comment by albertoestarrona** [comment]
Solved with PR #253

![captura de pantalla 2018-03-02 a la s 14 11 24](https://user-images.githubusercontent.com/33098363/36919749-f67c1d9e-1e23-11e8-8bcf-264502bbb65d.png)

**Comment by albertoestarrona** [comment]
Solved with PR #253
