### ISSUE TITLE
[UI] Update status strings (nation and user status)

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#252]
## Feature / Issue
> In a list of nations (and elsewhere) we can see the status of a nation, and the status of join/leave operations by a user.
> We use global strings to tell the user of these operations.
> Update the strings as shown below.
> Create new global string values as needed.
> Each status has a color, also, in the global colors. The "warning color" is a global value.

Status Text for Nations:
- nation draft = Draft (medium gray)
- nation pending create = Pending (light gray)
- nation accepted = show as a normal nation, status field shows the population.
- nation rejected = Rejected (warning color)

Status Text for Users joining Nations:
- user pending join = Joining (light gray)
- user pending leave = Leaving (light gray)
- user join rejected = Banned (warning color)

## Acceptance criteria
- [ ] Update global strings with status strings

## Additional information
Keep ... in mind

**Comment by mimetic** [comment]
![nations with status 0 3 2 v5](https://user-images.githubusercontent.com/30195/36920453-912cd752-1e15-11e8-935c-12ddd9fe4dc4.png)

**Comment by seland** [comment]
@mimetic What string can we use for leaving failed status?

**Comment by florianlenz** [comment]
@seland what do you mean by " leaving failed status"?

**Comment by seland** [comment]
@florianlenz What should we show on nation if user tried to leave it, but the operation was unsuccessful.
