### ISSUE TITLE
[UI] Rename Elizabot

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#256]
## Feature / Issue
> Some users might confuse the ElizaBot with Lucy.
> Change the name of the ElizaBot to "Dr. Freud Bot"
> Change the introductory text of the ElizaBot to be clearly NOT a Lucy bot. 

## Acceptance criteria
- [x] Rename Elizabot in the list of chats
- [ ] Change the introductory Elizabot text (consult with Jacob Cox)

ElizaBot code is in vendor/elizabot.js.
The current initial text possibilities that should be are these:

> this.elizaInitials = [
> 		'How do you do.  Please tell me your problem.',
> 		'Please tell me what\'s been bothering you.',
> 		'Is something troubling you ?',
> 		'Im here. Talk to me.',
> 		'Talk to me',
> 		'Top of the morning to you.',
> 		'Thanks for waking me up',
> 	]

**Comment by mimetic** [comment]
David says, use the following text for this.elizaInitials:
'Hi, I am Dr. FreudBot, your resident therapist. What is bothering you?',
'Herr Professor Doktor FreudBot here, your therapy bot. What has been troubling you?',
'I am the Pangea therapy bot, Dr. FreudBot, ready to help. I am not a real therapist, I just play one in this app.',
'Talk to me! I am Dr. FreudBot. Tell me about your mother.',
'Hallo, Dr. FreudBot here. I am not a real Freudian. I am not real. Are you? Are you sure?'

**Comment by albertoestarrona** [comment]
Done in `feature/Chat-UI-0.3.3`
