### ISSUE TITLE
[UI] Add Elizabot to list of chats in "Chats" list 

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#257]
## Feature / Issue
> The list of chats (Chat tab) shows nations with chats that have begun.
> The list of chats should also include any built-in 'bots, e.g. ElizaBot. ElizaBot will link to the Eliza Chat screen, while chats for nations will link to the appropriate nation chat screen.
> Other bots are coming, so consider a generic way to add items to this list of chats.

## Acceptance criteria
- [x] Add ElizaBot to the list of chats. Resort the list to put ElizaBot in the right place.

## Additional information
Keep ... in mind

**Comment by albertoestarrona** [comment]
What would be the name for the Bot?

**Comment by mimetic** [comment]
Currently the only bot we have is ElizaBot, whose name will be "Dr. FreudBot".
I suggest add a new set of global strings, "bot", where we can add bot names. I believe a FAQBot and/or HelpBot is coming, so best to use the global strings file.

**Comment by albertoestarrona** [comment]
Need to bot's Icon for the UI in the list

**Comment by mimetic** [comment]
Try these:

[chatbot.zip](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/files/1783142/chatbot.zip)

**Comment by albertoestarrona** [comment]
Done in `feature/Chat-Ui-0.3.3`
