### ISSUE TITLE
[UI] Use new "signal" icon for chat list

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#258]
## Feature / Issue
> To show the level of activity in a chatroom, we use a "signal" icon in the list of chats, under the "Chat" tab.

Sample icon:
![signal_icon_0 3x](https://user-images.githubusercontent.com/30195/37006019-2498aec2-208b-11e8-95cd-3bc3d85dba9f.png)

## Acceptance criteria
- [x] Install new signal icon into the code, show the appropriate icon depending on a calculation of business.

Icons attached below.

[signal_strength_icon on dark.zip](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/files/1783003/signal_strength_icon.on.dark.zip)

**Comment by albertoestarrona** [comment]
Added them in `feature/Chat-UI-0.3.3`
