### ISSUE TITLE
[chat] Include user id in the message

### ISSUE THREAD

**Issue by SeniorMobileDeveloper** [Bit-Nation/BITNATION-Pangea-mobile#260]
## Feature / Issue
Currently there 's no way to identify the user of the incoming messages.
We should include the user id in the message object.

## Acceptance criteria
- Messages from the same user should have the same id.

**Comment by seland** [comment]
@SeniorMobileDeveloper @florianlenz It seems to be done, can we close that?

**Comment by SeniorMobileDeveloper** [comment]
Yes, it 's already fixed and merged to develop.

**Comment by seland** [comment]
Cool, closing then.
