### ISSUE TITLE
Android APK-Release crashes when entering ChatScreen

### ISSUE THREAD

**Issue by albertoestarrona** [Bit-Nation/BITNATION-Pangea-mobile#275]
## Feature / Issue
When compiling the release APK (using: https://facebook.github.io/react-native/docs/signed-apk-android.html),  it crashes when the user enters a chat (ChatScreen), no matter if it's Bot or Nation. The logcat error is this:

`03-09 22:48:11.718 16566 16606 E AndroidRuntime: java.lang.NullPointerException: uriString
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at android.net.Uri$StringUri.<init>(Uri.java:476)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at android.net.Uri$StringUri.<init>(Uri.java:466)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at android.net.Uri.parse(Uri.java:438)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at com.reactnativenavigation.react.ImageLoader.loadImage(ImageLoader.java:18)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at com.reactnativenavigation.params.parsers.TabIconParser.parse(TabIconParser.java:19)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at com.reactnativenavigation.params.parsers.ScreenParamsParser.parse(ScreenParamsParser.java:57)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at com.reactnativenavigation.controllers.NavigationCommandsHandler.push(NavigationCommandsHandler.java:40)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at com.reactnativenavigation.bridge.NavigationReactModule.push(NavigationReactModule.java:182)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:162)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
03-09 22:48:11.718 16566 16606 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
03-09 22:48:11.718  2639  3199 W ActivityManager:   Force finishing activity co.bitnation/com.reactnativenavigation.controllers.NavigationActivity`

This bug could be solved for the release using this and modifying the local file:
https://github.com/wix/react-native-navigation/issues/1365

Still needs to check a better solution for this issue.

## Acceptance criteria
- [ ] When the release APK it's created and there's no crash at Chat Screen, without the need of a temporal hack.

**Comment by seland** [comment]
It's an issue when tabIcon is set for the screen which is not actually in the tab bar. Error is pretty non-descpritive, but we checked it and with high probability it's the reason of the error. 
So, you should check if you have such screens (actually the screen where you have a crash).
I'm closing it, feel free to reopen if that solution is not working for you.
