### ISSUE TITLE
Chat backend for PROD not working

### ISSUE THREAD

**Issue by albertoestarrona** [Bit-Nation/BITNATION-Pangea-mobile#276]
## Feature / Issue
When setting `https://bitnation-chat-backend.herokuapp.com/`as the URL for the chat backend, the Chat does not work properly: you can send a messages, but they are not stored and are erased when the screen it's reloaded.

## Acceptance criteria
- [ ] When the messages are stored and the functionality it's exactly the same as when using the testing URL

**Comment by florianlenz** [comment]
Fixed.
