### ISSUE TITLE
Blank word boxes on Create Wallet page

### ISSUE THREAD

**Issue by infinitechaos** [Bit-Nation/BITNATION-Pangea-mobile#277]
I'm running an LGV20 VS995 with Android 7.0, security patch level Feb. 1, 2018, build NRD90m, software version VS9951AA.

On the Create Wallet page the word boxes are blank for both group 1 and group 2.

This is on the latest release that was just pushed to the Play Store today.

![capture _2018-03-10-15-34-18](https://user-images.githubusercontent.com/8084414/37247935-1ed4ef2c-2479-11e8-9119-532e18c63481.png)

**Comment by florianlenz** [comment]
@seland @albertoestarrona @SeniorMobileDeveloper That's a huge problem. Never happened to me. Any suggestion's how to fix it?

**Comment by florianlenz** [comment]
@infinitechaos Did you try to close the app and try to create the wallet again?

**Comment by infinitechaos** [comment]
@florianlenz I did close the app and restart it multiple times but the boxes were still showing blank. I just uninstalled it and reinstalled it and now the words are showing up in the boxes.

**Comment by seland** [comment]
I assume it was the issue in communication between Pangea libs and Pangea, since we refactored that part a lot, I'm closing the issue. In case you have it again, feel free to reopen.
