### ISSUE TITLE
4th row covered up by keyboard when verifying private key

### ISSUE THREAD

**Issue by infinitechaos** [Bit-Nation/BITNATION-Pangea-mobile#278]
![capture _2018-03-10-15-46-41](https://user-images.githubusercontent.com/8084414/37248004-00a18658-247b-11e8-9d67-e0eba2ec67c0.png)

The keyboard covers up the 4th row of text entry boxes when verifying a private key. It's still possible to enter text into them by selecting the first of the three in the 4th row, entering the word, then hitting 'next' on the keyboard to get to the next box. But it's a little cumbersome if it can be fixed.

**Comment by florianlenz** [comment]
Hi. @infinitechaos we gonna change the process of verification in the next week's to another model. So I will just close this for now. Feel free to open another issue in case this happens with the new verification process as well.
