### ISSUE TITLE
[UI] Fix placeholder text in Wallet: Send

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#286]
## Feature / Issue
> The placeholder text in "Wallet:Send Money" currently shows "1.02". That text was only to demonstrate how it could look, but it is confusing.

## Acceptance criteria
- [x] Change "1.02" to "0.00000" (See attached image for final result)

![screen shot 2018-03-12 at 6 30 15 pm](https://user-images.githubusercontent.com/30195/37317742-de50471a-2623-11e8-96d7-7d9cf3c65701.jpg)

**Comment by albertoestarrona** [comment]
Solved in #298
