### ISSUE TITLE
[db] pull in database from pangea lib's

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#293]
## Feature
Till now pangea lib's handled our database. Since we gonna drop pangea lib's we now need to take care of it in the mobile repo. 

You can find the current db logic [here](https://github.com/Bit-Nation/BITNATION-Pangea-libs). 

The database should be located under `services/database`

## Acceptance criteria
- Take migration's from pangea lib's.
- Implement the main database service. 
- Test's ;)

**Comment by seland** [comment]
It's already done in 0.4.5, closing.
