### ISSUE TITLE
[profile] The new Profile logic

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#296]
## Feature / Issue

We will work more identity / profile centric. We enable user to have many id's (profiles). Let's imaging I have profile `A` and profile `B` and I am logged in with profile `A` when I then join nation `Liberland` I only joined it within the context of the profile. When I log out and login with `B` I can join with that profile as well. 

That mean's we need to change a LOT of thing's:
1. Have a session for the user
2. Store the decrypted private key's in a temporar storage that is secure (maybe in the app state but not in the main state container). 
3. New way of creating an profile
4. New confirm of private key
5. Wallet (we will also add another token)

### Dependency:
- [ ] Eslint must be finished
- [ ] New Database must be in place

### Tasks:
- [ ] create profile
- [ ] Recover profile
- [ ] "Logout"
- [ ] Backup profile
- [ ] Lock app 
- [ ] profile setting's

**Comment by seland** [comment]
Done in release 0.4.5.
