### ISSUE TITLE
Interaction flow: logged in mode

### ISSUE THREAD

**Issue by kentdahlgren** [Bit-Nation/BITNATION-Pangea-mobile#3]
## Feature / Issue
Usage behavior when a user opens the Pangea application and is already logged in

## Acceptance criteria
This feature is complete when the application interaction is consistent with that which is documented in the attached interaction flow diagram 

## Additional information
See attached files
[Logged In Mode v1.pdf](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/files/1573757/Logged.In.Mode.v1.pdf)

**Comment by seland** [comment]
@kentdahlgren It seems to be outdated. I'm closing it, but feel free to reopen it if needed.
