### ISSUE TITLE
[ci] Build hangs after tests step regardless of tests status

### ISSUE THREAD

**Issue by seland** [Bit-Nation/BITNATION-Pangea-mobile#313]
## Feature / Issue
Build on Bitrise hangs right after tests step. There are two examples:
https://www.bitrise.io/build/e45dbb4297b674c3
https://www.bitrise.io/build/4e339a7f5e49bda9

## Acceptance criteria
CI build rejects if tests are failed and goes further if tests passed.

## Additional information
It works fine earlier, so may be related with that PR - https://github.com/Bit-Nation/BITNATION-Pangea-mobile/pull/304.

**Comment by seland** [comment]
@william2958 It seems that removing Realm tests by [that commit](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/commit/ebac44beac76f234f43a7f39b646c91d2db7792b) resolves the issue. Hope this helps.

**Comment by florianlenz** [comment]
Maybe we need to close the realm instances. Tho that would be very anyoing. Maybe there is another way.

**Comment by seland** [comment]
@florianlenz Yeah, you're probably right. Here is a [comment](https://github.com/realm/realm-js/issues/593#issuecomment-264136534) about that.

**Comment by seland** [comment]
I fixed it by adding --forceExit flag to test script - check out this [commit](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/commit/13c93d408c2799d6174310503b30735644d3d2d5). It seems to be not the issue with CI, so I close the issue.
