### ISSUE TITLE
When verifying recovery seed of new wallet, I cannot see the text boxes while typing

### ISSUE THREAD

**Issue by Mnuzz** [Bit-Nation/BITNATION-Pangea-mobile#315]
## Feature / Issue
This occurs when verifying the recovery seed of a new wallet. When clicking a box to type in, I am unable to see the screen. The keyboard moves the text boxes out of the area of visibility. This happens in both horizontal and vertical orientations. 
![screenshot_2018-03-21-06-19-03](https://user-images.githubusercontent.com/1613498/37713690-eda0ecda-2cd4-11e8-8235-a5980b84562b.png)

## Additional information
I am using a Samsung Galaxy Note 4, Android 6.0.1.

**Comment by seland** [comment]
It is already fixed, area above keyboard on key verification process screen is scrollable now.
