### ISSUE TITLE
No decimal on keyboard layout when using ETH wallet to send transaction. Also no transaction confirmation notification.

### ISSUE THREAD

**Issue by infinitechaos** [Bit-Nation/BITNATION-Pangea-mobile#325]
![capture _2018-03-25-14-02-08](https://user-images.githubusercontent.com/8084414/37880026-de2c73d6-3036-11e8-93cd-8175c7082a50.png)

No decimal point on keyboard layout.

![capture _2018-03-25-14-04-50](https://user-images.githubusercontent.com/8084414/37880022-d13875f8-3036-11e8-897b-beb195c3f82b.png)

Upon sending a transaction I received no confirmation after hitting 'send'. The keyboard disappeared but aside from that the screen remain unchanged and was given no indication the transaction had been submitted to the blockchain.

**Comment by seland** [comment]
Both of reported issues were fixed in 0.4.0 and 0.5.3, so I'm closing it.
