### ISSUE TITLE
incorrect sorting of capitalized and non capitalized names on the nation list

### ISSUE THREAD

**Issue by paulofonseca-me** [Bit-Nation/BITNATION-Pangea-mobile#329]
![4e390d1e-aece-4f2b-a643-36bfb775a102](https://user-images.githubusercontent.com/3208148/38002435-3e336740-322a-11e8-84b6-80934cfadc2b.jpeg)
## Feature / Issue
> As a user I would like to see the list of nations sorted correctly, in a way that capitalized and non capitalized names are together, so that I can easily find a nation when scrolling through the list. 

## Acceptance criteria
- [ ] When I scroll through the list of nations, “Liberland” and “laureland” are in the same “L” section. 

## Additional information
Currently, “laureland” with an non-capitalized name, is showing up in the end of the list of nations.

**Comment by seland** [comment]
Fixed in 0.4.1.
