### ISSUE TITLE
Keyboard covering message window on iPhone chat  

### ISSUE THREAD

**Issue by Farmerjohn2022** [Bit-Nation/BITNATION-Pangea-mobile#330]
## Feature / Issue
> As a user ... (remove this)

## Acceptance criteria
- [ ] When i ... then ... (remove this)

## Additional information
Keep ... in mind

**Comment by Farmerjohn2022** [comment]
Sorry not sure how to do this. Using iPhone 7 with 11.2.6 running. Not getting text window or access to send button in chat from the location of the keyboard, changing view doesn’t help either.

**Comment by xsttx** [comment]
@Farmerjohn2022 is this still an issue? If not, I'll close this issue.
