### ISSUE TITLE
[iOS] App restores wallet but not profile

### ISSUE THREAD

**Issue by TaelsMD** [Bit-Nation/BITNATION-Pangea-mobile#331]
## Feature / Issue
Apple iPhone 8 Plus iOS 11.2.6
> As a user I would like the profile to be completely restored as long as the wallet. The app shows the "Create a User Profile" screen instead of my old profile with my name, photo and location.  Messages from my old profile on chat are shown as if they were someone else.

![img_1726](https://user-images.githubusercontent.com/36716878/38098953-b34ad24a-334f-11e8-8f77-3dee7011902b.jpg)

**Comment by xsttx** [comment]
@TaelsMD can you please try to break down each of your points in different issues, so it's possible to track and solve one by one? Also please let us know what device those issues/ bugs are on (version and brand of Android or iOS etc) otherwise it's impossible for the team to work with.

**Comment by seland** [comment]
This one is the consequence of current application design. Implementing full restoration may be considered as an enhancement. However, I would like to close this specific issue and open a general one pointing root architectural issue.
@borjantrajanoski ping
