### ISSUE TITLE
[iOS] After restoring the wallet the app does not show that I am citizenship of a nation

### ISSUE THREAD

**Issue by TaelsMD** [Bit-Nation/BITNATION-Pangea-mobile#332]
## Feature / Issue
Apple iPhone 8 Plus iOS 11.2.6
> The app knows I am citizen of a nation by displaying the message "You are citizen of ..." (but only after closing and reopening the app after the first restore).

**Comment by seland** [comment]
That part of the app was significantly changed and issue is not reproducing now, so I'm closing it. Feel free to reopen in case you have it again.
