### ISSUE TITLE
[iOS] Nations gradually appearing on the first sync

### ISSUE THREAD

**Issue by TaelsMD** [Bit-Nation/BITNATION-Pangea-mobile#333]
Apple iPhone 8 Plus iOS 11.2.6
## Feature / Issue
> I noticed it takes about 2-3 minutes for the app to sync on the first launch. When it does, nations start appearing in the chronological order that they were created.

## Acceptance criteria
- Maybe it would be interesting to have a "first sync, please wait" screen in the first time the app is launched.

**Comment by seland** [comment]
Closing the issue, in case you have it again, please reopen.
