### ISSUE TITLE
[iOS] All users without profile are identified as "A" on the chat

### ISSUE THREAD

**Issue by TaelsMD** [Bit-Nation/BITNATION-Pangea-mobile#335]
Apple iPhone 8 Plus iOS 11.2.6
## Feature / Issue
> It seems like all users without profile are displayed as capital "A" on the nation chat. If you do not have a profile, that makes messages from other people without profile to display as if it were yours (blue box).

## Acceptance criteria
- Maybe the chat could be available only to people with profile to avoid that. Maybe some kind of unique identified could be implemented.

![img_1724](https://user-images.githubusercontent.com/36716878/38098854-6c437a46-334f-11e8-9e27-4f70ac5a5bac.jpg)

**Comment by florianlenz** [comment]
Hi, 

thank you for reporting this. If you don't have an profile your name is `Anonymous` which is the reason for the capital `A`. However, this chat is really just a demo (which is the reason for the missing "id" system). We will upgrade to a more sophisticated system in the next weeks. I will close this for now.
