### ISSUE TITLE
The Bitnation chat is no longer updating, I have responded to the most recent message I can see on multiple occassions and the next time I open the chat again  my comment is gone and the same older comment is the last thing I can see.

### ISSUE THREAD

**Issue by Savage2288** [Bit-Nation/BITNATION-Pangea-mobile#336]
## Feature / Issue
> As a user ... (remove this)

## Acceptance criteria
- [ ] When i ... then ... (remove this)

## Additional information
Keep ... in mind I have only noticed this happening specifically in the Bitnation chat area. "The notifications from messages are not working" is the comment I have attempted to respond to multiple times.
![bitnation chat bug](https://user-images.githubusercontent.com/37993086/38182588-1e5cb3f2-3600-11e8-883b-6509330867e5.jpg)

**Comment by florianlenz** [comment]
Hi, 

thanks for opening an issue. I can't reproduce it. We will upgrade to a more sophisticated and reliable system in the next week's since the current chat is more a kind of demo. Stay tuned.
