### ISSUE TITLE
[iOS] Impossible to send (withdraw) ETH

### ISSUE THREAD

**Issue by zavan** [Bit-Nation/BITNATION-Pangea-mobile#338]
I don't know if this is a bug or just not yet implemented, but on iOS, on the `sendMoney` screen, after typing the amount and pasting the address (both valid), the "Send" button is never enabled, even after hiding the keyboard:

![img_4080](https://user-images.githubusercontent.com/1722965/38585233-8296ad64-3cef-11e8-8720-72c5f38e04b7.PNG)
![img_4081](https://user-images.githubusercontent.com/1722965/38585234-82b5a462-3cef-11e8-9f4a-d9c7b00d027b.PNG)
iOS 11.3 - iPhone 8 Plus, Bitnation 1.0.3 (2) (from TestFlight).

---

In case anyone encounter the same problem, I was able to "withdraw" all funds by transforming my mnemonic (the 24 words of the wallet) into a raw private key (by using the [same lib](https://github.com/bitcoinjs/bip39) as the app):

```js
var bip39 = require('bip39');
var pk = bip39.mnemonicToEntropy(yourSeed);
console.log(pk);
```

And using the result in the "Private key" option of [MyCrypto.com](https://mycrypto.com/#send-transaction) to send a transaction to my wallet.

**Comment by zavan** [comment]
Could it be because my keyboard shows a comma (`,`) instead of a point (`.`) because of my location settings on iOS?
![img_4082](https://user-images.githubusercontent.com/1722965/38586845-c91e4660-3cf5-11e8-8ddc-371188a6c550.jpg)

**Comment by seland** [comment]
@zavan Yes, I think comma is the problem, the number just wasn't treated as valid, so send is disabled. Thanks for reporting
