### ISSUE TITLE
[iOS] Can’t type on chat, keyboard covers text box

### ISSUE THREAD

**Issue by zavan** [Bit-Nation/BITNATION-Pangea-mobile#339]
![57e6cc45-c4b2-49a8-b69a-9b86f0c646a5](https://user-images.githubusercontent.com/1722965/38587808-469427ba-3cf9-11e8-8a92-a942199477a1.png)

iOS 11.3, Bitnation 1.0.3 (2) (from TestFlight)

**Comment by zavan** [comment]
Only happens when going “Home -> Nations -> Select nation -> Chat”, when going “Home -> Chat -> Select nation” it works.

**Comment by florianlenz** [comment]
Thank you guy's. We will look into it.

**Comment by seland** [comment]
Closing the issue, in case you have it again, please reopen.
