### ISSUE TITLE
[iOS] Keyboard prevents from creating nation

### ISSUE THREAD

**Issue by zavan** [Bit-Nation/BITNATION-Pangea-mobile#340]
When creating a nation on iOS, the keyboard covers the submit button. To make the keyboard go away you have to select the “Nation name” field and tap “return” on the keyboard.

![daa58db6-9b25-433a-88cc-54b8e470122f](https://user-images.githubusercontent.com/1722965/38588579-0d3fd988-3cfd-11e8-8a31-8627025f8b4b.png)

iOS 11.3, Bitnation 1.0.3 (2) (from TestFlight)

**Comment by florianlenz** [comment]
Thank you. We will have a look at it.

**Comment by seland** [comment]
@zavan Thanks for reporting. In current UI you should be able to hide keyboard by tapping outside of any fields as well. Bottom bar is not pushed by keyboard intentionally to not reduce active space on the screen. So, it's a trade off more than a bug. 
I'm going to close the issue, feel free to reopen it if you have any thoughts on it.
