### ISSUE TITLE
When I try to write in a chat, my keyboard is covering the text box where I'm typing

### ISSUE THREAD

**Issue by Razaberry** [Bit-Nation/BITNATION-Pangea-mobile#346]
## Feature / Issue
> https://drive.google.com/open?id=1Qdp1GKR4Kjb53vTlGznoqqFa0SWnjCDY

## Acceptance criteria
- https://drive.google.com/open?id=1Qdp1GKR4Kjb53vTlGznoqqFa0SWnjCDY

## Additional information
iPhone X

**Comment by Razaberry** [comment]
Solvable just by tapping on a non-text-field... but its unintuitive.

**Comment by seland** [comment]
Thanks for reporting, this is the same issue as #339, so I'll close that one to prevent duplicating.
