### ISSUE TITLE
switch from web3 to ethers.js

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#357]
## Feature / Issue
Currently we are using web3. Since it's not a very usable library in combination with react native, we should switch to [ethers.js](https://github.com/ethers-io/ethers.js/) for our own use. 

## todo's
- [ ] implement a signer that ask's the user to sign a transaction
- [ ] Remove all old libraries (web, `rn-nodeify`)

**Comment by florianlenz** [comment]
@william2958 What we also need is a new interface for signing an transaction. It should have:
- a heading
- a short text
- a slider which set the gwei of the transaction

do you think that would be possible todo?

**Comment by william2958** [comment]
Yes it definitely is possible to do variable gas costs in the service call, but this would be implemented somewhere in the UI, so I'm not sure what how I would implement it? However I can definitely set it so that more parameters in the transaction can be set variably.
