### ISSUE TITLE
Unable to restore wallet 

### ISSUE THREAD

**Issue by mlarkento** [Bit-Nation/BITNATION-Pangea-mobile#366]
## Feature / Issue
Restore wallet

## Acceptance criteria
When i attempt to restore my wallet the app text doesn't act as a button to start the process and there is no button visible. 

## Additional information
My phone was damaged and, although I've installed the app on the new phone, and I have my record of the 24 keys to restore the wallet, I'm having difficulty with the process in the app as there is no visible way to initiate the process.

**Comment by mlarkento** [comment]
Zero State is building multiple  Bitnations and losing access is a major impediment to moving forward.

**Comment by florianlenz** [comment]
@mlarkento Thanks for reporting. Can you attach an screenshot?

**Comment by mlarkento** [comment]
![20180509_132603](https://user-images.githubusercontent.com/27616517/39829740-5f82f80a-538d-11e8-92dd-ef572c31fced.jpg)
![20180509_132514](https://user-images.githubusercontent.com/27616517/39829756-6cd36aa8-538d-11e8-9457-771b0639bc9c.jpg)

**Comment by mlarkento** [comment]
Screen does not scroll.

**Comment by florianlenz** [comment]
yes - I see. There is a button but it's hidden by the menu. We gonna fix this.

**Comment by mlarkento** [comment]
Ty.

**Comment by florianlenz** [comment]
@swmd - how long will it take you to fix this? It's an `XS` from my point of view.

**Comment by mlarkento** [comment]
Florian,
Any updates?  It's been almost a week without being able to restore the wallet.  Is there a temporary workaround available? 
Thank you. :-)

**Comment by florianlenz** [comment]
Ping @swmd 

@mlarkento there is no work around in the app but I can build you a cli node js tool

**Comment by mlarkento** [comment]
Florian,
I'm not familiar with "cli node js tools" but I'm willing to learn. If it isn't to difficult to do, then yes, I'd appreciate that. Thank you. 👍

**Comment by florianlenz** [comment]
@mlarkento sorry for the late response. Since we change our app heavily with the next release we need to migrate private key's which means that we need to write a tool to get the private key from the 24 word's so that you can access your fund's. However, I would like to test it with you together. I will ping you when it's ready.

**Comment by mlarkento** [comment]
Thank you 👍

**Comment by florianlenz** [comment]
Sorry for letting you wait. 
Please follow this instructions: https://steemit.com/bitnation/@infinitechaos/pangea-v0-4-5-june-8-release-note-important

**Comment by mlarkento** [comment]
Thank you @florianlenz . My wallet is restored.
