### ISSUE TITLE
Error trying to create nation

### ISSUE THREAD

**Issue by Razaberry** [Bit-Nation/BITNATION-Pangea-mobile#369]
## Feature / Issue
> Tried to create a nation, filled out all the info, said yes to the ETH transaction fee, and then was confronted with this error. No ETH was moved.

This happened on a Samsung Galaxy Note 8 & an iPhone SE (slightly diff error message)

![image uploaded from ios](https://user-images.githubusercontent.com/4132724/40247149-056fe436-5afe-11e8-82ab-38907c2a7364.jpg)

**Comment by xsttx** [comment]
This bug was fixed in the 1.3.3 release.
