### ISSUE TITLE
Too may buttons to access chat

### ISSUE THREAD

**Issue by yodrew** [Bit-Nation/BITNATION-Pangea-mobile#370]
## Feature / Issue
As an Android user, I dislike having to press five buttons to get to my nation's chat. I frequently do not open Bitnation because of how long it will take to access the chat.

Chat is the central function of the app. Opening the app should, like Whatsapp, open my last chat. Or my last activity since turning my phone on. It could default to a list of chats if I have more than one and I haven't used the app in couple hours. 

The dashboard is currently useless to any but brand new users. It is not a point of access as it should be, but an obstacle.

## Acceptance criteria
When I can access my last Bitnation chat from the Android home screen in no more than two button presses, then using Bitnation will become a reasonable proposition and the issue can be closed as far as I am concerned.

**Comment by florianlenz** [comment]
@mimetic That's your topic :)

**Comment by seland** [comment]
@mimetic Any thoughts?

**Comment by mimetic** [comment]
We are working on improved UX/UI for Nations and Chat, so this issue will be resolved when we make those changes.

**Comment by yodrew** [comment]
Thanks!
