### ISSUE TITLE
[0.4.5] release preperation

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#372]
## Feature / Issue
Since we make will have an release with quite big changes we need to make sure everything is ready. 

## Acceptance criteria
- [ ] database migration's (florian)
- [ ] check the crypto part on the panthalassa side
- [ ] migration guide
- [ ] tell user to create a new private key since they won't have access with the old one anyway
- [ ] check if implementation's of spec's are correct

**Comment by seland** [comment]
Since 0.4.5 is done, I'll close it.
