### ISSUE TITLE
Wallet "receive" button text misaligned on Android

### ISSUE THREAD

**Issue by archermoon7** [Bit-Nation/BITNATION-Pangea-mobile#376]
## Feature / Issue
> As a user I would like to see the text "Receive" be vertically center aligned. 

## Acceptance criteria
- [ ] When I see it match the way the send button text displays, then this is a success.

## Additional information
This is displaying on a Samsung Note 8, Android 8.0.0
![walletreceivebutton](https://user-images.githubusercontent.com/39760558/40710515-726e9f2e-642b-11e8-8c6f-11231f49fc54.jpg)

**Comment by seland** [comment]
Thanks for reporting. UI design was changed since the issue is reported, so it can be reproduced anymore. Feel free to reopen it if you have it again.
