### ISSUE TITLE
[chat] Chat List

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#377]
## Feature / Issue
Hi,

since we need to have a private chat in this sprint, we need to be able to add people. This functionally might be known as "contacts". However, we need to keep it simple. Instead of having contracts we will only add people by there public key. So you will enter your public key and safe the public key. In the background you will have to fetch the profile from one of our nodes via http. After the profile was added a new entry is displayed in the chat section with that person. 

ask @mimetic if you have questions regarding the UI. For everything else Florian. 

## Acceptance criteria
- [x] add profile by public key
- [x] fetch profile from node
- [x] display in list of chat after fetching from node.

**Comment by seland** [comment]
It's already done in 0.5.3, so closing.
