### ISSUE TITLE
Pangea last version gets in permanent "Uploading"

### ISSUE THREAD

**Issue by manelomanu** [Bit-Nation/BITNATION-Pangea-mobile#392]
## Feature / Issue
> As a user of the Pangea Dapp last version 

## Acceptance criteria
- [ ] When i get into the dApp it gets stuck in a permanent Uploading... then I can't see the list of nations and my wallet gets "Update failed... 

## Additional information
Keep ... in mind

**Comment by florianlenz** [comment]
@manelomanu can you please add some screenshots?

**Comment by seland** [comment]
@manelomanu Please check out version 0.5.4 - it has performance improved and this issue may be related to that.

**Comment by seland** [comment]
Closing the issue, in case you have it again, please reopen.
