### ISSUE TITLE
[dapps] connect to remote computer

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#398]
## Feature / Issue
As a DApp developer I need to connect my computer with my pangea app in order to be able to develop a DApp. In order to connect my phone and the computer I need to scan a QR-Code displayed on my computer. 

The interface that scan the barcode should display what this is about e.g. "Scan barcode to connect to PC" and it should have a close button to close the "scanner interface". 

This component should be reusable. Maybe a callback or what ever can be passed it that will be triggered when scan succeed.  

## Acceptance criteria
- [x] should display heading that describes what it is about
- [x] should display a close button

**Comment by florianlenz** [comment]
2 days. Friday.

**Comment by hunght** [comment]
1 day. Monday.
