### ISSUE TITLE
Footer (applicable to all indicated screens)

### ISSUE THREAD

**Issue by kentdahlgren** [Bit-Nation/BITNATION-Pangea-mobile#4]
![footer](https://user-images.githubusercontent.com/32444135/34191901-6284bad6-e4ff-11e7-804a-5bf0d22c6b93.jpg)
## Feature / Issue
Consistent footer nav provided for all indicated screens (see each ticket created for each screen)

## Acceptance criteria
This issue is closed with the menu functionality is provided as defined for the specified screens (see each ticket).

## Additional information
See attached file.

## Needed:
- [ ] Icons for each (Kent is creating the one for Dashboard - ignore the one for Lucy
- [ ] Labels for each (should be self-explanatory but see Kent if there's questions) 

[icons.zip](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/files/1574228/icons.zip)

**Comment by mimetic** [comment]
Good if we can get higher resolution versions of the icons, for possible use as pictures.

**Comment by mimetic** [comment]
Also, I recall an earlier note where you suggest using an icon set already captured as a font.

**Comment by kentdahlgren** [comment]
The info I've found on-line indicates that icons can be png, which means we
don't have to mess with converting pngs into ttfs, which isn't working very
well

**Comment by florianlenz** [comment]
@kentdahlgren Yes, it seem's like that's possible (see [here](https://github.com/oblador/react-native-vector-icons#usage-as-png-imagesource-object))
