### ISSUE TITLE
[react_renderer] implement a react renderer

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#401]
## Feature / Issue
As a DApp developer I need to be able to render an UI in the mobile application. 

## Acceptance criteria
- [x] rendering of messages as described in the specs
- [x] rendering of modal as described in the specs
- [x] fully integrated render engine. 
- [x] support components listed in #415

**Comment by seland** [comment]
It's done on 1.1.0
