### ISSUE TITLE
[store] Google Play Store description update

### ISSUE THREAD

**Issue by ErkanKanden** [Bit-Nation/BITNATION-Pangea-mobile#407]
Please add russian translation to Google Play Store description: https://docs.google.com/document/d/16DLBgfmCNM6hYqm8a2rWJbXidb_Z0QRUq0rHfU0Haas/edit

Typo in the description text in English: Should be "world changing" and not "word changing"

**Comment by florianlenz** [comment]
@albertoestarrona Please take care of this and pass your estimation to @kevowevo .

**Comment by albertoestarrona** [comment]
This is already solved. Just wait for a few hrs for the update to be alive
