### ISSUE TITLE
Error in PanthalassaIdentityPublicKey method

### ISSUE THREAD

**Issue by swmd** [Bit-Nation/BITNATION-Pangea-mobile#414]
## Feature / Issue
> As a developer when I try to get the public key of the user from Android phone, I get the error below.
![screen shot 2018-06-22 at 3 21 22 pm](https://user-images.githubusercontent.com/12961158/41778747-f92a2770-762f-11e8-99ab-ebbff55e44dc.png)

The same method works well in iOS but not in Android.

## Acceptance criteria
- Get the public key from console

**Comment by albertoestarrona** [comment]
This is solved with #417
