### ISSUE TITLE
[upsteam] handle upstream call

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#419]
## Feature / Issue
Hi. We are using [protobuf](https://developers.google.com/protocol-buffers/) to serialize / deserialize information. Those information is send from panthalassa to pangea. Via the bridge (more later on). You need to deserialize the information in react native. 

There is a protobuf JS library. You will have to compile the protobuf file from panthalassa to the [json representation](https://github.com/dcodeIO/ProtoBuf.js/#using-json-descriptors) in order to use it. 

You have to [subscribe to Panthalassa events](https://facebook.github.io/react-native/docs/native-modules-ios.html#sending-events-to-javascript) in order catch the requests send by panthalassa.
```js
import { NativeEventEmitter, NativeModules } from 'react-native';
const { Panthalassa } = NativeModules;
```

After you got a request [(which looks like this)](https://github.com/Bit-Nation/panthalassa/blob/develop/api/pb/request.proto):
Every request contains a request id. 

After your processed a the call you have to call `Panthalassa.PanthalassaSendResponse` with: 
- id (the request id)
- data (a [response](https://github.com/Bit-Nation/panthalassa/blob/develop/api/pb/response.proto) - can be an empty `Response` if there is no need to return data to panthalassa)
- error (if something is wrong with the received data pass in an error or an empty string)
- timeout (timeout for the processing the response in seconds)

## Acceptance criteria
- [ ] Handle current protbuf requests
- [ ] should display error if program is unable to handle request

## Calls

__note about DRKey__
A DRKey is a double ratchet key. 
Double ratchet keys are are stored in two key value mappings. 

There is a key, a message number and a message key.

The `key` should have a mapping as it's value. In this mapping the key is the message number and the value is the message key. 

e.g.:

key = `0xf3`
msgNum = `4`
msgKey = `0xf2`

would be stored as: 
```js
{
   "0xf3" : {
      4: "0xf2"
   }
}
```

#### DRKeyStoreGet
fetch a message key by it's message number and the key

#### DRKeyStorePut
safe a message key under a key and a number

#### DRKeyStoreDeleteMK
delete message key by key and message number

#### DRKeyStoreDeleteKeys
Delete all message keys under a key

#### DRKeyStoreCount
count the message keys of a key

#### DRKeyStoreAll
Fetch all message keys

#### ShowModal
should show a modal with the given title and a page with the given layout (@seland)

#### SendEthereumTransaction
This should sign a ethereum transaction + send it. 

#### SaveDApp
Save a DApp to the DApp store.

**Comment by hunght** [comment]
@florianlenz 
1. where should i save the message data?, in Realm or just the in key-value local 
2. how do i get messageKey  from  
dRKeyStoreGet: {
    drKey: 1,
    messageNumber: 2,
  }

**Comment by florianlenz** [comment]
1. in realm. 
2. What exactly do you mean? The messageKey is not in the protobuf since it's a get request. If you are asking for how to get be message key based on the `dRKeyStoreGet` request, then you have to understand how they are persisted (which you can read in the issue)

**Comment by florianlenz** [comment]
I will close this. It's done.
