### ISSUE TITLE
Public key not loading from clipboard to chat interface

### ISSUE THREAD

**Issue by infinitechaos** [Bit-Nation/BITNATION-Pangea-mobile#425]
I receive the following error when attempting to initiate a chat dialogue with a valid public key in my clipboard:

![capture _2018-06-30-16-41-36](https://user-images.githubusercontent.com/8084414/42130047-bdc3ca44-7c8b-11e8-8c24-ea9fda31ddb3.png)

**Comment by SanderSpooner** [comment]
I am having the same issue.  I close the app and re-open. Same issue. The main menu along the bottom is responsive, but the selection on each page ( identity, nations, +Chat button) are unresponsive until after about 3 minutes.

I'm on Samsung Galaxay J7 Sky Pro, Model SM-S727VL, Android 6.0.1.

**Comment by Savage2288** [comment]
+1

**Comment by florianlenz** [comment]
Could you try it again?

**Comment by infinitechaos** [comment]
I woke up today and now have Jack, Savage, and Susanne in my contacts list in the chat interface. I'm not sure if it's because they added me while I was asleep or if it's because the action of me adding them yesterday before I went to sleep executed after a long wait.

**Comment by Savage2288** [comment]
i added infinitechaos today

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by seland** [comment]
There was an issue while exchanging profiles. The issue should not appear anymore, so I'm closing the ticket.

P.S. This screen is showing in case we can't identify anyone by public key you entered. Uploading of profiles happens on login, so if your partner can't add you try to logout and login again. It'll be improved in future releases.
