### ISSUE TITLE
My newly created nation still shows as pending

### ISSUE THREAD

**Issue by ravi9884** [Bit-Nation/BITNATION-Pangea-mobile#434]
## Issue
> As a user I would like to see my nation created when i paid the safe ether and the ether transaction is executed.

## Acceptance criteria
- When i submitted nation with safe gas and transaction executed then the nation should show up in the list of nations. But it still shows up as pending

## Additional information
nation: FreeMarket
ether address: 0x220740Bc7f7F86729652dA70B06cE4867bd99539

![img_9e0ba7dc5823-1](https://user-images.githubusercontent.com/6249312/42410589-d77c4316-81b9-11e8-96d3-7a17e78c107e.jpeg)

**Comment by seland** [comment]
@ravi9884 Please check out version 0.5.4 - I can see Freemarket nation created succesfully. If it's fixed, please close the issue.

**Comment by ravi9884** [comment]
It shows up in markets now. But it doesn’t show up under my nations

**Comment by seland** [comment]
"My nations" means only nations I have joined, but not nations I have created in the current implementation. 
This issue became the same as #353, so I'm closing it.
@ravi9884 Please check this [comment](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/issues/353#issuecomment-430751413) for details.
