### ISSUE TITLE
Android app loading issues

### ISSUE THREAD

**Issue by mrtnbsm** [Bit-Nation/BITNATION-Pangea-mobile#437]
## Feature / Issue
> As a user ... (remove this)

It takes several minutes for the settings tab to load (before the security, identify, pk buttons are clickable). 

The Nations field in the Dashboard tab and the Nations tab do not load at all (spinning circles) but perhaps that's because I haven't created any nations yet. 

The app version: 0.5.3

Android version: 8.0.0

## Acceptance criteria
- [ ] When i ... then ... (remove this)

## Additional information
Keep ... in mind

**Comment by seland** [comment]
@mrtnbsm Please check out version 0.5.4 - it has performance improved and this issue fixed.

**Comment by mrtnbsm** [comment]
Great work, seems to work fine now

**Comment by seland** [comment]
Thanks, I'm closing the issue then.
