### ISSUE TITLE
No decimal on the keyboard on both the XPAT escrow and Send Money screens on Android.

### ISSUE THREAD

**Issue by infinitechaos** [Bit-Nation/BITNATION-Pangea-mobile#445]
![capture _2018-07-21-19-23-35](https://user-images.githubusercontent.com/8084414/43041665-de9793d6-8d1b-11e8-9b85-fee390db07b0.png)

**Comment by seland** [comment]
@infinitechaos Thanks for reporting, we'll check this out.
