### ISSUE TITLE
[versioning] Make versions consistent across platforms

### ISSUE THREAD

**Issue by seland** [Bit-Nation/BITNATION-Pangea-mobile#448]
## Feature / Issue
At the moment latest Android release has version 0.5.4 and iOS release - 1.0.7. There are several reasons why we need to make them equal:
 - it's logical because iOS and Android apps actually have the same functionality and changes, so they should have the same version. 
 - we’re going to have some data migrations (not the database schema ones) in the future and for that we need to know current version and previous installed version and do some migrations if needed. For the clarity here we need to have consistent versions across platforms from the moment when we implement that migration infrastructure.

The challenge here is that Android and iOS versions are different too much, which means we can’t just make them both 0.5.5, 0.6.0 and even 1.0.0 (because it’s less than current 1.0.7).

## Suggestion / Solution
The most light solution is to change version of next release to 1.1.0 on both platforms. Since we're going to add a VM and ability to create own DApps it's quite a big change, which is good explanation of such big version change. 

## Acceptance criteria
- Versions of iOS and Android builds to be equal as soon as it's possible.

**Comment by florianlenz** [comment]
As discussed in the standup, the next version will be `1.1.0`.

**Comment by seland** [comment]
It's done on 1.1.0.
