### ISSUE TITLE
[chat] migration of chat

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#450]
## Feature / Issue

Our current chat use panthalassa to encrypt messages, but submitted & stored are they in pangea. Since we migrate the chat functionality to panthalassa (encryption, transport, storage etc) we have to apply a migration to all current stored messages. 

__Process of message migration__
1. Decrypt old message with panthalassa method (check out code in `src/sagas/chat/sagas.js` `onSessionsChange` method, here the decryption is performed).
2. Persist the plain message in panthalassa with the `Import` methods provided by Panthalassa. We're using services to interact with Panthalassa, for instance, you can add corresponding method to chat service (`src/services/chat/index.js`). In order to access services we're using a simple service container, you can check out how it's accessed from sagas.  
3. Delete the shared secrets, double ratchet keys and encrypted messages from Realm.

__Clean up of chat related methods__
We need to change sagas, reducers, actions and chat service as well to remove code that is not needed anymore on Pangea side. 

__Integrate new logic using Panthalassa__
Since messages are not stored on pangea anymore, we need to register listeners on panthalassa to wait for events. When a messages got e.g. delivered you will received an event that looks like this: 
```json
{
   "type": "MESSAGE:DELIVERED",
   "payload": {
       "message_id": "6273987623409823743",
       "message": "message data .......",
       "partner": "6f3........",
   }
}
```
We're using an upstream to send messages from Panthalassa to Pangea (`src/services/upstream/index.js`). It's using protobufs to send messages. We need to update compiled protobuf requests/responses with the new spec (needs to be taken from @florianlenz) using `npm run build:protofile`.
Then we need to add new protobuf request for type specified above (will be on the new spec).

Also, we need to do initial fetch from Panthalassa on login - all chats and last X messages of each chat.
> Methods will follow here

## Acceptance criteria
- [ ] Messages are correctly sent to Panthalassa and deleted from Pangea by migration process 
- [ ] Reducers, sagas, actions and service cleaned up from unused chat related methods
- [ ] Chats and last X messages of each chat are loaded on login 
- [ ] Chats are updating when new message is coming
- [ ] Send message is working correctly.

## Additional information
Constant X should be stored on `src/global/constant` under some descriptive name.

**Comment by seland** [comment]
Chat is now handled by Panthalassa starting from 1.1.0. Issue can be closed.
