### ISSUE TITLE
[chat] DApp message component

### ISSUE THREAD

**Issue by seland** [Bit-Nation/BITNATION-Pangea-mobile#451]
## Feature / Issue
DApp can post messages into the chat. That messages should look different from usual messages to inform user that they're sent by DApp. 

Some information about how messages from DApp should be handled described [there](https://github.com/florianlenz/pangea-specs/blob/i18n/dapps/requirements/chat_ui/customizable_chat.md). 

Tasks that needs to be done:
- [ ] Create DAppMessage component that will serve as a container for DApp messages. You may assume that every information you need in that component from Pangea (like DApp name, message information, etc) will be passed in as props. JSON layout provided by DApp developer will also be passed via props, but you don't need to handle it right now - there will be a separated component that will render provided layout, so you can just leave a place where to put it once it's ready.
- [ ] Implement UI of component, so it look fine on the chat (ask @mimetic about where to find specs and if you have related questions)
- [ ] Tests and docs. We're using jsdoc for documenting components and their props, check out any component in `src/components/common/`.

**Comment by mimetic** [comment]
- [ ] There should be a default layout, assuming the developer has NOT provided JSON layout. The default layout would use passed props, e.g. Title, Body, Status, etc. fields. See the sample UI layouts for and implement, at least, Title, Body, Status fields in the default layout.

**Comment by prameetc** [comment]
@seland Can this issue be closed? Or are there some more things that we need to consider?

**Comment by seland** [comment]
Done in 1.1.0.
