### ISSUE TITLE
New version and migration of previous account.

### ISSUE THREAD

**Issue by ebarakos** [Bit-Nation/BITNATION-Pangea-mobile#452]
After the deployment of the new version of the Pangea/Bitnation app, some months/weeks ago, I am experiencing the following: 

1) when I restore my account using my saved phrase, I can't access my created nations, it's like a new account has been created. 

2) every time I restore account using this same phrase, new accounts are being created, with different ETH deposit address for example, and they are saved separately on my mobile phone.

**Comment by seland** [comment]
Thanks for reporting, it was fixed in prior releases. Please reopen in case you have that issue on latest release (1.1.0) or later.
