### ISSUE TITLE
[panthalassa] todos

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#455]
## Feature / Issue
Panthalassa changed quite a lot, so we have to do some adjustments. 

__ui api__
We added a [UI api](https://github.com/Bit-Nation/panthalassa/tree/system_update/uiapi) that will send status updates from panthalassa to the client. The api works a bit like the upstream, but you don't need to send back a response. 

__upstream__
We changed the upstream protobuf. Please update the [request](https://github.com/Bit-Nation/panthalassa/blob/system_update/api/pb/request.proto) and the [response](https://github.com/Bit-Nation/panthalassa/blob/system_update/api/pb/response.proto)

**Comment by seland** [comment]
Done by #462.
