### ISSUE TITLE
UI: Change Text in Chat, Identity, Chat Menu

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#457]
## Feature / Issue
> As a user, the term "Public Key" is confusing. Joffy has discovered that most users are trying to use their wallet addresses to start chats. We need a name for the Public Key that is clear, and we need it easy to find and share.
Even though pasting the public key is a temporary method, management needs a solution now.

For details: see the latest UI sketches here: https://xd.adobe.com/spec/dbcd5e01-851d-4d74-4234-6b3b905ebadb-adfc/

## Acceptance criteria
- [ ] Change wording of bottom sheet for "New Chat": "Public Key" --> "Identity Key"
- [ ] Add "Share my Identity Key" to "more" menu in top-right of Chat List.
- [ ] Change wording of button in identity/profile screen, from "Share Public Key" to "Share Identity Key"
- [ ] Update the text of the error dialog for "Invalid or Missing Key" (see sketch for wording)

## Additional information
We will test the wording "Identity Key" vs. "Identity Public Key" until we find something users can use.

**Comment by seland** [comment]
Closed by #459
