### ISSUE TITLE
Bination-pangea does not recogize me as the creator & owner of my 2 nations

### ISSUE THREAD

**Issue by mlarkento** [Bit-Nation/BITNATION-Pangea-mobile#464]
## Feature / Issue
> After restoring my MLarkento account using the 24 words, I am unable to access my two nations as the owner and creator. In fact the software asks me to pay to join as a regular member.

## Acceptance criteria
- [ When i go to my 2 nations, then the software should recognize me as owner and creator. ]

**Comment by mlarkento** [comment]
@florianlenz Hi, do I need to provide additional info? TY.

**Comment by seland** [comment]
Current implementation of nations doesn't take ownership as membership and vice versa. It may be confusing, though. Anyway, it's caused by more deep architectural issues, that needs to be addressed. 
The issue is similar to #353 and therefore should be closed.
