### ISSUE TITLE
Decimal missing from keypad, cannot send fractions of an ether or xpat

### ISSUE THREAD

**Issue by mlarkento** [Bit-Nation/BITNATION-Pangea-mobile#470]
## Feature / Issue
Decimal missing from keypad, cannot send fractions of an ether or xpat

![mlarkento wallet with decimal ether](https://user-images.githubusercontent.com/27616517/44058994-e74b4cd4-9f1d-11e8-9643-87d333679cd3.jpg)
![send keypad missing decimal](https://user-images.githubusercontent.com/27616517/44059003-efa5e704-9f1d-11e8-8ad7-4a18b55c93ba.jpg)
![send screen whole numbers only](https://user-images.githubusercontent.com/27616517/44059005-efb908ca-9f1d-11e8-9dbd-b458dd91baac.jpg)

**Comment by mlarkento** [comment]
@florianlenz Hi, do I need to provide additional info? TY.

**Comment by mlarkento** [comment]
[FireShot Screen Capture #006 - 'Ethereum Transaction 0x3ad3395f66c9419597ec218b46323a0f51ce9891ef6a958e9abf3965bee2f2eb' - etherscan_io_tx_0x3ad3395f6.pdf](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/files/2284812/FireShot.Screen.Capture.006.-.Ethereum.Transaction.0x3ad3395f66c9419597ec218b46323a0f51ce9891ef6a958e9abf3965bee2f2eb.-.etherscan_io_tx_0x3ad3395f6.pdf)

**Comment by seland** [comment]
Thanks for reporting, this should be fixed in latest update (1.1.0). I'm closing the issue, feel free to reopen if you have it again.
