### ISSUE TITLE
[ui] Settings: Update UI

### ISSUE THREAD

**Issue by prameetc** [Bit-Nation/BITNATION-Pangea-mobile#472]
## Feature / Issue
> We need to match the design of the Settings screen with the updated specs found in: https://xd.adobe.com/spec/230e899d-f6c5-4936-7539-59dbab1a414d-553f/
> We need to create **standard rows** of different kinds, as found in the design documents (above).
> We need to create **standard inputs** of different kinds, e.g. buttons, toggles, etc.
> Once we have the standardized items, we can use them to rebuild the UI for the settings pages.
> This includes slight change to the design of the button in the main Settings Screen and in all the subscreens. Apart from this, we need to also fix the colors of the menu buttons to match the updated design.

## Blocking Tasks
None. Current settings are enough to start with, expect new settings to appear!

## Acceptance criteria
- [ ] Use standard, globally defined components, e.g. large rows, compact rows, section titles, etc. to rebuild the listings in the security pages
- [ ] Use standard, globally defined input components, e.g. toggle, checkbox, slider, etc.
- [ ] Create and implement icons for settings rows.
- [ ] Use the standard full-width, globally defined button for "SWITCH ACCOUNTS"
- [ ] Change the UI of the buttons in each sub-screen and the main screen of Settings.

**Comment by florianlenz** [comment]
Can you please estimate this issue?

**Comment by prameetc** [comment]
@florianlenz All the tasks will be completed by end of this week.

**Comment by prameetc** [comment]
This can be finished by tomorrow @kevowevo

**Comment by seland** [comment]
Done by #484.
