### ISSUE TITLE
[ui] Dashboard - Major UI Update

### ISSUE THREAD

**Issue by prameetc** [Bit-Nation/BITNATION-Pangea-mobile#495]
## Feature / Issue
> The dashboard can undergo some significant design changes to make the user experience a whole lot better. The way we display the nations and the wallets can be made better and we can go with dropdowns if required especially to display the user's current nations. 

For further info, check out this design for the dashboard screen

https://xd.adobe.com/spec/230e899d-f6c5-4936-7539-59dbab1a414d-553f/screen/f6d9688e-3c42-449d-b7c0-6452ebfb6d62/Dashboard/

## Acceptance criteria
- [ ] Make cards on the dashboard span the full length of screens.
- [ ] Create dropdowns (if required) for nations and wallet.
- [ ] Add suitable logos for wallet and nations.
- [ ] Update overall UI and small tweaks wherever required.

## Additional information
Feel free to add more stuff as they occur related to the main dashboard.

**Comment by prameetc** [comment]
@florianlenz @seland Let me know your thoughts on this issue.

**Comment by prameetc** [comment]
@mimetic Let me know if this can be closed as we may be doing away with the dashboard.

**Comment by xsttx** [comment]
Issue closed, no more dashboard in 1.4.1
