### ISSUE TITLE
Screen: Nations

### ISSUE THREAD

**Issue by kentdahlgren** [Bit-Nation/BITNATION-Pangea-mobile#5]
## Feature / Issue
Nations functionality (screen and function)

## Acceptance criteria
Satisfied when the screens deliver upon the look, feel, form, and function as defined in the attached document and as indicated in the attached interaction flow document

## Additional information
See attached. Seek kent for clarification
* If the app does not have a private key OR there is no wallet for payment OR there are not sufficient ETH funds in the wallet, THEN the "New" link used to create a new nation should NOT be visible.
* For 0.3, there is only one private key for the app. This key is used for the wallet and for nation creation. This will change in the future.

## Newest Screen Designs
https://invis.io/HTF508H5Z
Contact David Gross if you do not have permissions to see.

## NEEDED
* icons (Kent) (Icon are provided in the comments, below, in PNG format)
* label verbiage (should be obvious but we need to review)
* descriptive text for each interaction (needs to be defined and approved)

![nations](https://user-images.githubusercontent.com/32444135/34191928-924b1102-e4ff-11e7-973f-492c0bcce0d8.jpg)
[Nations Module v1.pdf](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/files/1574234/Nations.Module.v1.pdf)

**Comment by kentdahlgren** [comment]
![nations_2](https://user-images.githubusercontent.com/32444135/34192018-03b5878c-e500-11e7-82ee-30f3c2b57ecd.jpg)

**Comment by kentdahlgren** [comment]
![nations_3](https://user-images.githubusercontent.com/32444135/34192040-2608dcee-e500-11e7-92c8-7e2fbb674128.jpg)

**Comment by kentdahlgren** [comment]
![nations_4](https://user-images.githubusercontent.com/32444135/34192172-3ea6b7f2-e501-11e7-8917-2720089748cc.jpg)

**Comment by kentdahlgren** [comment]
See this most recent attachment for HTML and CSS 

[Bitnation Style Guide Sketch.zip](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/files/1583922/Bitnation.Style.Guide.Sketch.zip)

**Comment by mimetic** [comment]
Three icons for the menu bar (1/3 from top).

![add-group](https://user-images.githubusercontent.com/30195/34420281-5dc87570-ebce-11e7-97d9-b9829159248b.png)
![leave-group](https://user-images.githubusercontent.com/30195/34420283-5dd79960-ebce-11e7-926b-2cc8a3185cee.png)
![map](https://user-images.githubusercontent.com/30195/34420284-5de9cf22-ebce-11e7-8fdd-a6e6598de095.png)

**Comment by mimetic** [comment]
To make it easier, here are the three icons in zip file:
[3 icons.zip](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/files/1591892/3.icons.zip)
