### ISSUE TITLE
Bug: Sign-in Cancellation and Retry

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#501]
## Feature / Issue
> From the Accounts screen, if 
1. I enter my code
2. Tap OK
3. Then while the app is processing, I tap the Android "down" triangle (at bottom)
4. I return to the Accounts list, where I can tap an account and try to login.

> Going "back" should cancel the login attempt.

## Acceptance criteria
- [ ] Opening the Accounts List page should cancel any current attempts to login. (When app is "loading" after user submits code/password, using the Android navigation bar back button should result in a cancellation of the login attempt).

## Additional information
_The **Back button in the Android Navigation Bar** allows users to navigate recently viewed screens in reverse chronological order._

_Upward navigation allows users to navigate one level upwards within a single app’s hierarchy, until the app’s home or top-level screen is reached. For example, the Up arrow in a top app bar is a form of upwards reverse navigation.

Upward navigation should be implemented for all child screens in an app and follow platform guidance. **Android and web apps should use the Material Up action, while iOS apps should use the back button within an iOS Navigation Bar.**_

**Comment by hunght** [comment]
@mimetic @seland I could work on this one, seen I have done with the duplicate accounts issue

**Comment by hunght** [comment]
@mimetic for my understanding that we only cancel process login when the user taps the Android "down" triangle (at the bottom). And we don't change the process when user tap cancel button on iOS navigation bar?

**Comment by mimetic** [comment]
@hunght I believe the "down" button simply hides the keyboard. It shouldn't be a cancel button.

`Using the Android navigation bar back button should result in a cancellation of the login attempt`. In iOS, the cancel in iOS should cancel.

Consider the passcode screen for an Android device. You see the keyboard (no decimal point!), the entry field, a delete key, a checkmark key, and the left-pointing triangle ("back"). The Back triangle cancels the operation. 

The "Cancel" on iOS cancels the operation.

IMPORTANT: What I saw is that, if you move quickly, you can get two login operations going at once. Cancelling using the "back" triangle does NOT cancel the login operation — it just shows the login screen, but the login operation is still running. That definitely should not happen.

On iOS, I entered my code, and I was able to tap "cancel" immediately after. I then saw the Accounts screen...then the app jumped to the logged-in state!

`Upward` navigation means navigating in the hierarchy of screens, to a screen that is a source for "lower" screens. For Android, this is a little confusing because they have those three buttons at the bottom of the screen. 

See something like this: 
https://developer.android.com/training/design-navigation/ancestral-temporal
