### ISSUE TITLE
[UI] Documents/Notary: status, fields, actions

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#504]
## Feature / Issue
In order to finish the notary we need to have following updates:
- [ ] Add ability to upload document to blockchain:
  - Logic - use `DOCUMENT:NOTARISE` command on `PanthalassaCall` to upload the document.
  - UI - add button to upload the document, connect logic with the button.
- [ ] Display status of document uploading:
  - Logic - there is a field called `tx_hash` on the document model. We need to implement checking status of the transaction by tx hash and update the status field on documents. This should be done asynchronously (means we should wait for all tx statuses to resolve before we show documents list). Possible statuses are - `unknown` (while we're checking the status), `pending` (tx in progress), `accepted`, `failed` (tx failed). If we can't get the status by some reason it's not `failed`, but `unknown`. If there is no tx hash (because document was not being uploaded to blockchain) just don't show any status.
  - UI - add status field on the documents list, add status on document view.
- [ ] Display additional field related to document uploading - hash and signature.
  - Logic - update document type on Pangea side to contain that fields, update [mapping](https://github.com/Bit-Nation/BITNATION-Pangea-mobile/blob/develop/src/utils/mapping/documents.js) from Panthalassa representation.
  - UI - display fields on document view.
  - UI: TX value that automatically, copy when touched
  - UI: "Address" of the actual hash on the blockchain (not sure exactly what goes here, ask @florianlenz ) 
  - UI: Link to Etherscan with TX value
  - UI: Title + description
  - UI: Date/Time to report (probably last confirmation block? UNKNOWN)
  - UI: Signature of person submitting document, copy when touched

## Acceptance criteria
- [ ] All features implemented

## Additional information
UI can be found [here](https://xd.adobe.com/spec/ab0e10d4-de2d-4a00-6166-144f155c1887-dd3f/)

**Comment by prameetc** [comment]
@kevowevo This can be completed by Tuesday, the 18th

**Comment by mimetic** [comment]
@prameetc i recognize that you do not have screen designs for the fields yet.
