### ISSUE TITLE
[bug] UI: New document cannot hide keyboard

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#511]
## Feature / Issue
> As a user when creating a new document, I want to be able to see my entire page, esp. the uploaded image.
> If I enter text, the keyboard appears. However, if I am typing the title or desc, when I tap outside those fields, the keyboard does not go away. That is, the focus does not leave the field.
> If I then tap on the other field, then tap the background, focus does leave the field, and the keyboard goes away.
> What should happen is, if I tap outside the field, the focus goes away and the keyboard disappears.

## Acceptance criteria
- [ ] When I tap outside a text field (on a non-active area), the keyboard hides.

**Comment by prameetc** [comment]
Closing this issue as it is non-reproducable on most devices.
