### ISSUE TITLE
My wallet does not recognize the funds

### ISSUE THREAD

**Issue by SebastianJFM** [Bit-Nation/BITNATION-Pangea-mobile#520]
## Feature / Issue
> I have made a deposit in my wallet that is not recognized so I do not have it available, if it is recognized in my wallet address in Etherscan. The wallet is installed in a Huawei Metal GW smartphone. I installed the wallet in another smartphone (Huawei Mate 10 Lite), with the same seed but use the ETH network, because of this I generated another wallet address. So I do not know if I'm making an error, or it's the wallet.

## Acceptance criteria
- First I created an address in the XPAT testnet on a smartphone, then with the same seed create another address on the ETH network on another smartphone. In none of the smartphones does the Tokens recognize me.

## Additional information
Keep ... in mind
![screenshot_20180912-003154](https://user-images.githubusercontent.com/43194380/45401190-e6fa2b00-b625-11e8-91ce-fd142ddf12d8.png)
![screenshot_20180912-003220](https://user-images.githubusercontent.com/43194380/45401191-e6fa2b00-b625-11e8-80ea-b097971b0571.png)
![screenshot_20180912-003243](https://user-images.githubusercontent.com/43194380/45401192-e6fa2b00-b625-11e8-9db2-79e090b74573.png)
![screenshot_20180912-003259](https://user-images.githubusercontent.com/43194380/45401194-e792c180-b625-11e8-8992-72c77bfebfe9.png)
![screenshot_20180912-003320](https://user-images.githubusercontent.com/43194380/45401195-e792c180-b625-11e8-9545-f41295106b96.png)
![screenshot_20180912-003335](https://user-images.githubusercontent.com/43194380/45401196-e792c180-b625-11e8-9003-1dbdee83f3c7.png)
![screenshot_20180912-003406](https://user-images.githubusercontent.com/43194380/45401197-e792c180-b625-11e8-8f0e-c5e634cb44f1.png)

**Comment by SebastianJFM** [comment]
Hello, if I can update as you say. I only have one Nation available and I have even used the chat with another user, but still does not recognize the tokens.

**Comment by xsttx** [comment]
Hi SebastianJFM, please try to specifically "drag" the wallet screen down, to update the data on it.

**Comment by SebastianJFM** [comment]
Hola, no funciona aun. Solo resta alguna actualización.
  Gracias

**Comment by SebastianJFM** [comment]
Solo tengo una nación disponible luego de actualizar.

**Comment by marknuzz** [comment]
@SebastianJFM 

It's possible that your Pangea Wallet is set up to use the Rinkeby testnet. Try using the "Restore Account" feature (when first launching the app), and use your recovery seed. Make sure the wallet is on main net.

If you need assistance, please get in touch with me, mark@bitnation.co, or you can request help in our Telegram group, https://t.me/PangeaBitnation

**Comment by marknuzz** [comment]
Posting the text form of the link for reference: https://etherscan.io/address/0x0e3dd35Aeea11E0B52d0D3a0A30db714Da391F38
