### ISSUE TITLE
My bitnation app no update nations, event when a good connection available 

### ISSUE THREAD

**Issue by cmrestrepov** [Bit-Nation/BITNATION-Pangea-mobile#527]
## Feature / Issue
> As a user when I tried to join a nation, no nations appears available for me, event when a good connection is available. 

## Acceptance criteria
- [ ] When i ... then ... (remove this)

## Additional information
Keep ... in mind

**Comment by alleycatmews** [comment]
I have exactly the same problem. (ZTE Z862VL, Android 6.0.1) 

No nations appear on "Nations" section, except for the one I started (under the "All Nations" tab). Interestingly, mine does NOT show under "My Nations" tab but the status of my nation is "Status: Submission in progress..."

**Comment by Mnuzz** [comment]
This should now be fixed. Sorry for the inconvenience previously. See https://github.com/Bit-Nation/services.nation-cache/pull/1 for the changes that were made in order to facilitate this.
