### ISSUE TITLE
UI: Autopay transaction fees

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#530]
When the app should not ask for confirmation of gas payments when those payments are so small, that the use does not care. A better UX is automatically agree to very small payments, if the user has money in the wallet.

- [ ] Add a setting to allow autopayment of gas, below value M, when wallet has at least X ETH in it.
- [ ] Add setting for default “speed” for transactions, as shown in the transaction confirmation screen.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Mnuzz** [comment]
Closing this as it was requested by a dev team member and therefore redundant (the team has its own story board)
