### ISSUE TITLE
Insufficient funds when joining nation, despite having funds in wallet

### ISSUE THREAD

**Issue by Mnuzz** [Bit-Nation/BITNATION-Pangea-mobile#538]
## Feature / Issue
Android, Rinkleby (test network)

Shortly (after 5 minutes of receiving 0.05 ETH), and refreshing my Wallet page in the Pangea app, I am still unable to join a nation due to insufficient funds.

![image](https://user-images.githubusercontent.com/1613498/46586490-26087a00-ca34-11e8-8e2e-8a44fff881eb.png)

![image](https://user-images.githubusercontent.com/1613498/46586495-2acd2e00-ca34-11e8-8334-0446fd5f8bb0.png)

**Comment by xsttx** [comment]
Same issue when notarising documents, which is even more urgent.

**Comment by Mnuzz** [comment]
Triaged and planned

**Comment by Mnuzz** [comment]
Closing this as it was requested by a dev team member and therefore redundant (the team has its own story board)
