### ISSUE TITLE
Debugging + Design : Internal tools for debugging+design

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#57]
## Feature / Issue
> In order to see screens, debug, and design the app, I have to be able to change modes, and get assets, etc., without going through long processes.
> For example, to see the wallet, I need a way to magically get a wallet without going through the long secret key process.
> Like with video games: you don't want to play to level 65 every time you want to see the colors on screen 65!

## Acceptance criteria
- [ ] TURN ON/OFF refresh from blockchain.
- [ ] DO NOT MAKE ANY CHANGES ON THE NETWORK.
- [ ] ALL testing code must be in a single module. No testing code can exist inside the real code.
- [ ] Internal event system to update the UI must work, e.g. change a nation definition and the UI gets the message and updates, in all places (Nations, Dashboard, etc.)
### Nations:
- [ ] Ability to edit Nation to see how it looks (local data)
- [ ] Quick creation of test nation, e.g. "My Test Nation"
- [ ] Quick creation of 15 test nations with different names (long and short), to see lists of nations. Nations should have different status: (draft, pending, active, rejected)
### Wallet:
- [ ] Quick create a wallet
- [ ] Delete existing wallet (to start from beginning of process)
- [ ] Add money to wallet 
- [ ] Set wallet to 0 ETH
- [ ] Set wallet to not enough money to create a nation (to see failure)
- [ ] Set wallet to enough money to create a nation (to see success)
### Profile:
- [ ] Delete profile
- [ ] Quick create test profile
### Chat:
- [ ] Quick create list of chats
- [ ] Quick create a chat with many messages
### Dashboard:
- [ ]  Sample log file of activities, to see in the Activity panel
- [ ] Quick create lists of nations (same as above)

## Additional information
It is very hard and slow (and sometimes impossible) to debug and design without this system. Not having it is holding up a lot of my work.

**Comment by albertoestarrona** [comment]
Closed until next requirement from @mimetic
