### ISSUE TITLE
Store User's Profile info on Panthalassa

### ISSUE THREAD

**Issue by albertoestarrona** [Bit-Nation/BITNATION-Pangea-mobile#59]
## Feature / Issue
The App's current version stores the User's Profile information only into the device memory so it does not persists through several uses. Need to implement the saving of this information in Panthalassa.

## Acceptance criteria
App should stores User's Profile information, persists and be accesible also from all versions (mobile and desktop). Please provide me the functions to implement this behavior on the mobile version.

**Comment by florianlenz** [comment]
Hi,

checkout [this](https://github.com/Bit-Nation/Panthalassa/blob/develop/src/profile/profile.js#L17). The `ProfileInterface` provide all functions you need. You can get an instance of this service by importing the service container from `src/services/container.js`. If you have questions just ask me.
