### ISSUE TITLE
Documentation for Developing on Mac OS X Incomplete

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#60]
## Feature / Issue
> The instructions in Project Setup are incomplete.

## Acceptance criteria

* [x] Add: Install CocoaPods (https://cocoapods.org)
* [ ] Add the following procedure after checking out a branch:
>npm install
> cp .env.dev.example to .env
> cd ios
> pod install
> cd ..

[ ] Add ESLint setup: Combination of these :
> 1) To set the Google  JavaScript Style Guide as default
Open the [﹍Code Style. JavaScript﹍](https://www.jetbrains.com/help/webstorm/code-style-javascript.html) page (in the Settings/Preferences dialog (⌘,), choose  Editor | Code Style | JavaScript), click Set from, and then choose Predefined Style |Google JavaScript Style Guide. The style will replace your current scheme.
> 2)  http://www.codeblocq.com/2016/03/Setup-ESLint-in-WebStorm/

## Additional information
If you don't like the Google JavaScript Style Guide, then change the above instructions.

**Comment by florianlenz** [comment]
@mimetic thx. I will take this issue.

**Comment by florianlenz** [comment]
@mimetic do you mind checking #62 this and review it? I didn't added the things you mentioned in the second point because they are not related to changeing an branch. You just do it once you clone the project.

**Comment by florianlenz** [comment]
@mimetic Why did you reponed it? I merged the pull request with the changes.

**Comment by mimetic** [comment]
Because it needed changes. So, an issue should not be reopened? Should I start a new issue, even to work on something that was an issue before?

**Comment by florianlenz** [comment]
Yes start a new one once you need other stuff.
