### ISSUE TITLE
Centralize visual styles.

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#61]
## Feature / Issue
> Currently, Some visual styles are set inside of components. See the file, src/components/common/NationListItem.js
> All visual styling should be in central, global style files

## Acceptance criteria

* [ ] Create central styling files and method
* [ ] Move local visual styling to one or more global style files
  * [x] Nations
  * [x] Wallet
  * [x] Profile
  * [ ] Chat
  * [ ] Dashboard
  * [ ] Components

## Additional information

**Comment by mimetic** [comment]
➤ David Gross commented:

I have created the central styling system, including styles, colors, and (new!) strings.
However, the wallet is not built with it. For speed, let's move this to 0.3.2.

**Comment by seland** [comment]
Closed, since we want to change the approach of working with styles.
