### ISSUE TITLE
Global UI Strings file

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#67]
Text for the UI should be stored in a global file so that it is easy to make changes. 
For example, a "label" for a form field should be stored in this global file. That is, in a form, the label "Nation Name" should be stored in the global file.

## Acceptance criteria

* [ ] [This](https://github.com/AlexanderZaytsev/react-native-i18n) library is integrated to provide internationalization.
* [ ] File structure configured for localization, like ./src/global/strings/en.json and so on. 
* [ ] Everything is split up into separated objects (scopes), like:

```
legalCodeCommon: 'Common Law',
legalCodeCivil: 'Civil Law',
```

should be

```
"legalCode": {
"common": "Common Law",
"civil": "Civil Law"
}
```

(note the .json format), and used like Strings.t('legalCode.common').

* [ ] Strings file cleaned up from everything except infrastructure for string internationalization, like formatter functions should be removed (we have formatters in ./src/utils/formatters.js) and so on.

**Comment by seland** [comment]
@mimetic @albertoestarrona  We can integrate [this library](https://github.com/fnando/i18n-js#setting-up) to have strings separated and ground basis for internationalization. What do you think?

**Comment by mimetic** [comment]
Don't know the library, but an excellent idea. Get this into the system early.
Only question — will there be problems with right-to-left languages, e.g. Arabic? I can't imagine why, but worth a glance.

**Comment by mimetic** [comment]
Move to later sprint, and many issues already discussed.
