### ISSUE TITLE
Mobile app runtime error

### ISSUE THREAD

**Issue by SeniorMobileDeveloper** [Bit-Nation/BITNATION-Pangea-mobile#68]
When I try to run the app, I got the following error.

> $ npm run ios

`Error: src/services/container.js:19
 19: const ethWeb3Instance = web3(ethDaemon, ee, ethUtilsInstance);
 ^^^^^^^^^^^^^^^^ EthUtilsInterface. This type is incompatible with the expected param type of
 15: export default function web3Factory(node: JsonRpcNodeInterface, ethUtils: EthUtilsInterface, networkAccess: boolean): Promise<Web3> {
 ^^^^^^^ boolean. See: node_modules/BITNATION-Panthalassa/src/ethereum/web3.js:15`

This error is occurred in Panthalassa, please fix this issue quickly.

**Comment by florianlenz** [comment]
@seland not till now but I will do that. @SeniorMobileDeveloper let me try to reproduce it.
