### ISSUE TITLE
Screens: profile

### ISSUE THREAD

**Issue by kentdahlgren** [Bit-Nation/BITNATION-Pangea-mobile#7]
## Feature / Issue
the ability for users to create and edit a profile. 

## Acceptance criteria
Satisfied when the application function and look and feel reflects that which is specified in the attached images and interaction flow (see associated ticket for look and feel) 

## Additional information
See attached images and document 

## Newest Screen Designs
https://invis.io/HTF508H5Z
Contact David Gross if you do not have permissions to see.

## NEEDED
* Icons
* labels
* help verbiage authoring and approval

**Comment by xsttx** [comment]
@kentdahlgren should we ask for people's email addresses? Isn't that counter-intuitive for privacy?

**Comment by kentdahlgren** [comment]
It is. We discussed it and it was an oversight on my part. It’s to be removed. Good catch
