### ISSUE TITLE
Panthalassa async configuration

### ISSUE THREAD

**Issue by seland** [Bit-Nation/BITNATION-Pangea-mobile#70]
## Issue
There is a fundamental issue in service container, actually ethWeb3Instance is NOT a Web3 instance, but IS a promise that resolves into Web3 instance, however we pass it as Web3 instance to another constructors. That surely leads to crash on using Web3 instance methods (since there is no actually an instance, but promise).

## Possible solutions
Export not a container object but promise that returns a container. Requires changes across all the app.

**Comment by florianlenz** [comment]
Yes I would love to return a promise and I have todo it anyway's in the future. Do you want todo it or should I?

**Comment by seland** [comment]
@florianlenz I'll do that.
