### ISSUE TITLE
Add ESLint install to setup document for new developers

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#74]
## Feature / Issue
> Devs will find it useful to have ESLint installed.
> Setting up ESLint for Webstorm isn't 100% obvious if you don't know ESLint.
> Recommendation: Set up ESLint for React Native.

## Acceptance criteria
- [ ] Add install and setup instructions to the developer setup information page:

## Global Install

Use global install because otherwise, you have to reinstall if you reinstall the project.

### Global Installation and Usage
If you want to make ESLint available to tools that run across all of your projects, we recommend installing ESLint globally. You can do so using npm:

$ npm install -g eslint
You should then setup a configuration file:

$ eslint --init
After that, you can run ESLint on any file or directory like this:

$ eslint yourfile.js
Any plugins or shareable configs that you use must also be installed globally to work with a globally-installed ESLint.

Note: eslint --init is intended for setting up and configuring ESLint on a per-project basis and will perform a local installation of ESLint and its plugins in the directory in which it is run. If you prefer using a global installation of ESLint, any plugins used in your configuration must also be installed globally.

## Additional information
Keep ... in mind

**Comment by florianlenz** [comment]
@mimetic Eslint does not depend webstorm (and vise versa). It's an command line tool (yes, you can use it with webstorm but that makes no sense because we all develop on different IDE's).

**Comment by mimetic** [comment]
Kent wants a working setup that we can recommend to new developers, and I thought this could part of that recommendation. Of course, they can do what they wish.
