### ISSUE TITLE
no suitable peers available

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#78]
##  Issue
When running the light node I am getting this error: `Failed to retrieve data from network     err="no suitable peers available"`. See [here](https://github.com/Bit-Nation/react-native-eth-daemon/issues/12) for more details. It seem's like that it takes some time to solve the problem so it might be better to go with infura.io for this release. That's a bid more centralised but work's at least.

**Comment by seland** [comment]
Closing it since it's old and doesn't seem to be related to the current app state.
