### ISSUE TITLE
[wallet] connect wallet with backend

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#85]
## Feature
We need to connect the pangea lib's wallet with the UI in order to send / receive eth.

## Acceptance criteria
- [x] send eth
- [ ] receive eth
- [x] sync accounts

## Additional information
- Keep the promise rejection in mind

**Comment by seland** [comment]
@florianlenz Do we need to do something to receive money?

**Comment by florianlenz** [comment]
Not really. We just need to display the correct address.
