### ISSUE TITLE
Wallet: Key flow issues

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#87]
## Fixes
- [x] ~Verify Private Key: Testing Mode, so I don't have to enter all words to test UI!~ Moved to issue #108.
- [x] Either we create a graphic to demonstrate the screens, OR we have to make a reduced version with 24 words. Use graphic in UX-UI/UI/Production/Assets/demo-secret-key-entry.png
- [x] Create Private Key: ~Remove "Previous" on first screen showing rows of words to write.~ Make "Previous" inactive on first row.
- [x] Create Private Key: Remove "Done" on all screens showing words to write. 
- [x] Create Private Key: Next on 4th screen (last of Group 1 of words) shows an alert, which leads to the second group of words. However, when using previous to go backward, if alert has been shown, to NOT show it again when using Next. That is, the alert shows once, then not again.
- [x] Create Private Key: Next on last screen (which shows words 20-24) shows an alert. The alert "OK" goes to "Verify Key"
- [x] After previous "OK", we do not go to "Congradulations" screen, we go to Verify Secret Key.
- [x] Verify Private Key: Remove "Done" until very end.
- [x] Verify Private Key: "previous" and "next" should go to group 1 and group 2 screens, not prev/next words.
- [x] ~Verify Private Key: "Done" should appear on keyboard only if all words filled out correctly. Same as "Done" at top of screen.~
- [x] Verify Private Key: Do not allow entry of uppercase letters.
- [x] ~Text on many screens follows the InVision UI designs, but the UX has new text which should be used. Sorry. (Low priority!)~

**Comment by seland** [comment]
@mimetic 
> Create Private Key: Remove "Previous" on first screen showing rows of words to write.
So there is no way to go back on previous row if user accidentally tap next twice?

**Comment by seland** [comment]
@mimetic 
> Verify Private Key: "Done" should appear on keyboard only if all words filled out correctly. Same as "Done" at top of screen.

What keyboard button should be shown on last field if not all words filled out? I think "Done" is the best one, which is close the keyboard (as it currently does). Do you have another ideas on that?

**Comment by seland** [comment]
- [ ] Verify Private Key: Testing Mode, so I don't have to enter all words to test UI!
Moved to issue #108.

**Comment by seland** [comment]
- [ ] ~Verify Private Key: "Done" should appear on keyboard only if all words filled out correctly. Same as "Done" at top of screen.~
This is not possible, since we can't check if words are correct or not. "Done" appears at the top of the screen if all words are filled out (are not empty). "Done" on keyboard appears for last field (because it doesn't have next field).

**Comment by seland** [comment]
- [ ] ~Text on many screens follows the InVision UI designs, but the UX has new text which should be used. Sorry. (Low priority!)~
Moved into 0.3.2, where we will have consistent UI designs.
