### ISSUE TITLE
Wallet: Receive: Sharing

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#89]
## Feature / Issue
> Since chat is not ready, we cannot share ETH addresses on our chat to allow someone to send money.
> It is common to transfer ETH from outside Bitnation.
> Therefore, we need a way to share a Bitnation wallet address outside the system, e.g. email, chat, etc.

## Acceptance criteria
- [ ] Make "Share" button on Wallet Receive screen share a wallet address via system sharing tools (e.g. email, chat, etc.) These are the user configurable phone sharing tools. On iOS, they usually include email and message. 
- [ ] Sharing should include the wallet address as a string, ~AND the QR code.~

**Comment by seland** [comment]
According to #94 we remove QR code in milestone 0.3.1. I'll remove it from checkpoints for now. We can reopen it later in next milestone.
