### ISSUE TITLE
UI: Switch: Label extends outside View

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#90]
## Feature / Issue
> The label text is extending outside the View element in simulator. Might do so in real app? Bug?
See the SwitchLabeled.js component. Styles are in global/Styles.js

## Acceptance criteria
- [ ] Text should stay inside the View!

## Additional information
Keep ... in mind

**Comment by albertoestarrona** [comment]
Ready, global styles updated
