### ISSUE TITLE
Dashboard: Change "Demo" to "Coming Soon"

### ISSUE THREAD

**Issue by mimetic** [Bit-Nation/BITNATION-Pangea-mobile#92]
## Feature / Issue
> Current Dashboard shows "Demo" over some panels. The graphic should read "Coming Soon".

## Acceptance criteria
- [ ] Change "Demo" to "Coming Soon". The branch, feature/create-nations-screen has done this, and when merged, will solve this issue, because David created a new graphic and updated the code there.

## Files affected:
- src/components/common/DemoImage.js
- src/assets/images/demo.png, demoImage.png, demoImage@2x.png, demoImage@3x.png

**Comment by florianlenz** [comment]
@mimetic Why did you assign it to me? I am not a RN dev :D

**Comment by seland** [comment]
I close it, since we decide to remove all non-functional content from dashboard.
