### ISSUE TITLE
[wallet] send money - remove icon

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#93]
##  Issue
The icon right to the address should be removed. We will maybe add it again in the next releases. 
<img width="392" alt="bildschirmfoto 2018-01-23 um 00 08 18" src="https://user-images.githubusercontent.com/16626192/35249563-c6f4ab82-ffd2-11e7-9ac8-7e990d53b546.png">

## Acceptance criteria
- [ ] icon should be removed

## Additional information
@mimetic Can you update the wireframes etc according to this?

**Comment by seland** [comment]
@florianlenz Do you mean QR code icon?

**Comment by florianlenz** [comment]
I don't think it's an QR code. But I think we are talking about the same thing (icon right to the address)

**Comment by mimetic** [comment]
It is a button for scanning a QR code to fill in the address field. Can we scan QR codes?

**Comment by seland** [comment]
@mimetic QR code scanner was working for iOS, but still not working for Android. So we dropped it for this release on both platforms.

**Comment by mimetic** [comment]
OK
