### ISSUE TITLE
[wallet] receive money - remove QR code

### ISSUE THREAD

**Issue by florianlenz** [Bit-Nation/BITNATION-Pangea-mobile#94]
## Issue
Please remove the QR code for now. It seem's to not work on android so we need to drop it. 

## Acceptance criteria
- [ ] I should not see the QR code anymore

## Additional information
@mimetic Can you update the mockups and wireframes?

**Comment by mimetic** [comment]
OK, the QR scan button is not required for 0.3.2
@seland should remove it from the current UI.
