### ISSUE TITLE
Problem with Ethereum address at Create Nations

### ISSUE THREAD

**Issue by albertoestarrona** [Bit-Nation/BITNATION-Pangea-mobile#98]
## Feature / Issue
There is a problem when Create Nations and the Ethereum Address after calling the lb.

## Acceptance criteria
- [ ] Whe we are able to catch the valid Address from the new Nation

**Comment by florianlenz** [comment]
already solved.

**Comment by Fernandomolica** [comment]
How can I fix It?

Em 24 de jan de 2018 8:43 PM, "Alberto Estarrona" <notifications@github.com>
escreveu:
